DELETE FROM nex_core.language_translations WHERE page_key = 'template-master-4';

INSERT INTO nex_core.language_translations (translation_id, language_code, page_key, label_key, label_value)
VALUES
    -- General & Search
    (gen_random_uuid(), 'th', 'template-master-4', 'title', 'หัวข้อ Master 4'),
    (gen_random_uuid(), 'en', 'template-master-4', 'title', 'Master 4 Title'),
    (gen_random_uuid(), 'th', 'template-master-4', 'category', 'หมวดหมู่'),
    (gen_random_uuid(), 'en', 'template-master-4', 'category', 'Category'),
    (gen_random_uuid(), 'th', 'template-master-4', 'description', 'คำอธิบาย'),
    (gen_random_uuid(), 'en', 'template-master-4', 'description', 'Description'),
    (gen_random_uuid(), 'th', 'template-master-4', 'status', 'สถานะ'),
    (gen_random_uuid(), 'en', 'template-master-4', 'status', 'Status'),
    (gen_random_uuid(), 'th', 'template-master-4', 'all', 'ทั้งหมด'),
    (gen_random_uuid(), 'en', 'template-master-4', 'all', 'All'),
    (gen_random_uuid(), 'th', 'template-master-4', 'active', 'ใช้งาน'),
    (gen_random_uuid(), 'en', 'template-master-4', 'active', 'Active'),
    (gen_random_uuid(), 'th', 'template-master-4', 'inactive', 'ยกเลิก'),
    (gen_random_uuid(), 'en', 'template-master-4', 'inactive', 'Inactive'),
    (gen_random_uuid(), 'th', 'template-master-4', 'search_title', 'ค้นหาชื่อ...'),
    (gen_random_uuid(), 'en', 'template-master-4', 'search_title', 'Search name...'),
    (gen_random_uuid(), 'th', 'template-master-4', 'search_placeholder', 'ค้นหาข้อมูล...'),
    (gen_random_uuid(), 'en', 'template-master-4', 'search_placeholder', 'Search data...'),
    
    -- Table Headers
    (gen_random_uuid(), 'th', 'template-master-4', 'id', 'ID'),
    (gen_random_uuid(), 'en', 'template-master-4', 'id', 'ID'),
    (gen_random_uuid(), 'th', 'template-master-4', 'customer_name', 'ชื่อลูกค้า'),
    (gen_random_uuid(), 'en', 'template-master-4', 'customer_name', 'Customer Name'),
    (gen_random_uuid(), 'th', 'template-master-4', 'origin', 'ต้นทาง'),
    (gen_random_uuid(), 'en', 'template-master-4', 'origin', 'Origin'),
    (gen_random_uuid(), 'th', 'template-master-4', 'destination', 'ปลายทาง'),
    (gen_random_uuid(), 'en', 'template-master-4', 'destination', 'Destination'),
    (gen_random_uuid(), 'th', 'template-master-4', 'cargo_type', 'ประเภทสินค้า'),
    (gen_random_uuid(), 'en', 'template-master-4', 'cargo_type', 'Cargo Type'),
    (gen_random_uuid(), 'th', 'template-master-4', 'weight', 'น้ำหนัก'),
    (gen_random_uuid(), 'en', 'template-master-4', 'weight', 'Weight'),
    (gen_random_uuid(), 'th', 'template-master-4', 'priority', 'ความสำคัญ'),
    (gen_random_uuid(), 'en', 'template-master-4', 'priority', 'Priority'),
    (gen_random_uuid(), 'th', 'template-master-4', 'delivery_date', 'วันที่จัดส่ง'),
    (gen_random_uuid(), 'en', 'template-master-4', 'delivery_date', 'Delivery Date'),
    (gen_random_uuid(), 'th', 'template-master-4', 'manage', 'จัดการ'),
    (gen_random_uuid(), 'en', 'template-master-4', 'manage', 'Manage'),

    -- Summary Cards
    (gen_random_uuid(), 'th', 'template-master-4', 'total_items', 'รายการทั้งหมด'),
    (gen_random_uuid(), 'en', 'template-master-4', 'total_items', 'Total Items'),
    (gen_random_uuid(), 'th', 'template-master-4', 'items', 'รายการ'),
    (gen_random_uuid(), 'en', 'template-master-4', 'items', 'Items'),

    -- Actions
    (gen_random_uuid(), 'th', 'template-master-4', 'add_data', 'เพิ่มข้อมูล'),
    (gen_random_uuid(), 'en', 'template-master-4', 'add_data', 'Add Data'),
    (gen_random_uuid(), 'th', 'template-master-4', 'import', 'Import'),
    (gen_random_uuid(), 'en', 'template-master-4', 'import', 'Import'),
    (gen_random_uuid(), 'th', 'template-master-4', 'export', 'ส่งออก'),
    (gen_random_uuid(), 'en', 'template-master-4', 'export', 'Export'),
    (gen_random_uuid(), 'th', 'template-master-4', 'view', 'เรียกดู'),
    (gen_random_uuid(), 'en', 'template-master-4', 'view', 'View'),
    (gen_random_uuid(), 'th', 'template-master-4', 'edit', 'แก้ไข'),
    (gen_random_uuid(), 'en', 'template-master-4', 'edit', 'Edit'),
    (gen_random_uuid(), 'th', 'template-master-4', 'delete', 'ลบ'),
    (gen_random_uuid(), 'en', 'template-master-4', 'delete', 'Delete'),
    (gen_random_uuid(), 'th', 'template-master-4', 'column_settings', 'ตั้งค่าคอลัมน์'),
    (gen_random_uuid(), 'en', 'template-master-4', 'column_settings', 'Column Settings'),

    -- Modals (CRUD)
    (gen_random_uuid(), 'th', 'template-master-4', 'add_new_data', 'เพิ่มข้อมูลใหม่'),
    (gen_random_uuid(), 'en', 'template-master-4', 'add_new_data', 'Add New Data'),
    (gen_random_uuid(), 'th', 'template-master-4', 'edit_data', 'แก้ไขข้อมูล'),
    (gen_random_uuid(), 'en', 'template-master-4', 'edit_data', 'Edit Data'),
    (gen_random_uuid(), 'th', 'template-master-4', 'view_data', 'รายละเอียดข้อมูล'),
    (gen_random_uuid(), 'en', 'template-master-4', 'view_data', 'Data Details'),
    (gen_random_uuid(), 'th', 'template-master-4', 'cancel', 'ยกเลิก'),
    (gen_random_uuid(), 'en', 'template-master-4', 'cancel', 'Cancel'),
    (gen_random_uuid(), 'th', 'template-master-4', 'save_data', 'บันทึกข้อมูล'),
    (gen_random_uuid(), 'en', 'template-master-4', 'save_data', 'Save Data'),
    (gen_random_uuid(), 'th', 'template-master-4', 'saving', 'กำลังบันทึก...'),
    (gen_random_uuid(), 'en', 'template-master-4', 'saving', 'Saving...'),
    (gen_random_uuid(), 'th', 'template-master-4', 'close', 'ปิด'),
    (gen_random_uuid(), 'en', 'template-master-4', 'close', 'Close'),

    -- Form Fields
    (gen_random_uuid(), 'th', 'template-master-4', 'enter_customer_name', 'ระบุชื่อลูกค้า'),
    (gen_random_uuid(), 'en', 'template-master-4', 'enter_customer_name', 'Enter customer name'),
    (gen_random_uuid(), 'th', 'template-master-4', 'enter_origin', 'ระบุต้นทาง'),
    (gen_random_uuid(), 'en', 'template-master-4', 'enter_origin', 'Enter origin'),
    (gen_random_uuid(), 'th', 'template-master-4', 'enter_destination', 'ระบุปลายทาง'),
    (gen_random_uuid(), 'en', 'template-master-4', 'enter_destination', 'Enter destination'),
    (gen_random_uuid(), 'th', 'template-master-4', 'enter_cargo_type', 'ระบุประเภทสินค้า'),
    (gen_random_uuid(), 'en', 'template-master-4', 'enter_cargo_type', 'Enter cargo type'),
    (gen_random_uuid(), 'th', 'template-master-4', 'enter_weight', 'ระบุน้ำหนัก'),
    (gen_random_uuid(), 'en', 'template-master-4', 'enter_weight', 'Enter weight'),
    (gen_random_uuid(), 'th', 'template-master-4', 'select_priority', 'เลือกความสำคัญ'),
    (gen_random_uuid(), 'en', 'template-master-4', 'select_priority', 'Select priority'),
    (gen_random_uuid(), 'th', 'template-master-4', 'normal', 'ปกติ'),
    (gen_random_uuid(), 'en', 'template-master-4', 'normal', 'Normal'),
    (gen_random_uuid(), 'th', 'template-master-4', 'urgent', 'ด่วน'),
    (gen_random_uuid(), 'en', 'template-master-4', 'urgent', 'Urgent'),
    (gen_random_uuid(), 'th', 'template-master-4', 'pending', 'รอดำเนินการ'),
    (gen_random_uuid(), 'en', 'template-master-4', 'pending', 'Pending'),
    (gen_random_uuid(), 'th', 'template-master-4', 'in_progress', 'กำลังดำเนินการ'),
    (gen_random_uuid(), 'en', 'template-master-4', 'in_progress', 'In Progress'),

    -- Delete Confirmation
    (gen_random_uuid(), 'th', 'template-master-4', 'confirm_delete_title', 'ยืนยันการลบข้อมูล'),
    (gen_random_uuid(), 'en', 'template-master-4', 'confirm_delete_title', 'Confirm Data Deletion'),
    (gen_random_uuid(), 'th', 'template-master-4', 'deleting', 'กำลังลบ...'),
    (gen_random_uuid(), 'en', 'template-master-4', 'deleting', 'Deleting...'),
    (gen_random_uuid(), 'th', 'template-master-4', 'delete_data', 'ลบข้อมูล'),
    (gen_random_uuid(), 'en', 'template-master-4', 'delete_data', 'Delete Data'),
    (gen_random_uuid(), 'th', 'template-master-4', 'delete_confirm_msg', 'คุณแน่ใจหรือไม่ว่าต้องการลบข้อมูล'),
    (gen_random_uuid(), 'en', 'template-master-4', 'delete_confirm_msg', 'Are you sure you want to delete data'),
    (gen_random_uuid(), 'th', 'template-master-4', 'cannot_undo', 'การกระทำนี้จะไม่สามารถย้อนกลับได้'),
    (gen_random_uuid(), 'en', 'template-master-4', 'cannot_undo', 'This action cannot be undone'),

    -- Column Settings
    (gen_random_uuid(), 'th', 'template-master-4', 'column_settings_title', 'ตั้งค่าการแสดงผลตาราง'),
    (gen_random_uuid(), 'en', 'template-master-4', 'column_settings_title', 'Table Display Settings'),
    (gen_random_uuid(), 'th', 'template-master-4', 'select_columns_to_show', 'เลือกคอลัมน์ที่ต้องการแสดง'),
    (gen_random_uuid(), 'en', 'template-master-4', 'select_columns_to_show', 'Select columns to display'),
    (gen_random_uuid(), 'th', 'template-master-4', 'sort_data', 'เรียงลำดับข้อมูล'),
    (gen_random_uuid(), 'en', 'template-master-4', 'sort_data', 'Sort Data'),
    (gen_random_uuid(), 'th', 'template-master-4', 'no_sort', 'ไม่เรียง'),
    (gen_random_uuid(), 'en', 'template-master-4', 'no_sort', 'No Sort'),
    (gen_random_uuid(), 'th', 'template-master-4', 'sort', 'เรียง'),
    (gen_random_uuid(), 'en', 'template-master-4', 'sort', 'Sort'),

    -- Feedback / Alert Messages
    (gen_random_uuid(), 'th', 'template-master-4', 'no_data_found', 'ไม่พบข้อมูล'),
    (gen_random_uuid(), 'en', 'template-master-4', 'no_data_found', 'No data found'),
    (gen_random_uuid(), 'th', 'template-master-4', 'require_customer_name', 'กรุณาระบุชื่อลูกค้า'),
    (gen_random_uuid(), 'en', 'template-master-4', 'require_customer_name', 'Please enter customer name'),
    (gen_random_uuid(), 'th', 'template-master-4', 'require_origin', 'กรุณาระบุต้นทาง'),
    (gen_random_uuid(), 'en', 'template-master-4', 'require_origin', 'Please enter origin'),
    (gen_random_uuid(), 'th', 'template-master-4', 'require_destination', 'กรุณาระบุปลายทาง'),
    (gen_random_uuid(), 'en', 'template-master-4', 'require_destination', 'Please enter destination'),
    (gen_random_uuid(), 'th', 'template-master-4', 'save_success', 'บันทึกข้อมูลเรียบร้อยแล้ว'),
    (gen_random_uuid(), 'en', 'template-master-4', 'save_success', 'Data saved successfully'),
    (gen_random_uuid(), 'th', 'template-master-4', 'error_saving', 'เกิดข้อผิดพลาดในการบันทึกข้อมูล'),
    (gen_random_uuid(), 'en', 'template-master-4', 'error_saving', 'Error saving data'),
    (gen_random_uuid(), 'th', 'template-master-4', 'delete_success', 'ลบข้อมูลเรียบร้อยแล้ว'),
    (gen_random_uuid(), 'en', 'template-master-4', 'delete_success', 'Data deleted successfully'),
    (gen_random_uuid(), 'th', 'template-master-4', 'error_deleting', 'ลบข้อมูลไม่สำเร็จ'),
    (gen_random_uuid(), 'en', 'template-master-4', 'error_deleting', 'Error deleting data'),
    (gen_random_uuid(), 'th', 'template-master-4', 'error_changing_status', 'เปลี่ยนสถานะไม่สำเร็จ'),
    (gen_random_uuid(), 'en', 'template-master-4', 'error_changing_status', 'Error changing status'),
    (gen_random_uuid(), 'th', 'template-master-4', 'error_title', 'แจ้งเตือนข้อผิดพลาด'),
    (gen_random_uuid(), 'en', 'template-master-4', 'error_title', 'Error Notification'),
    (gen_random_uuid(), 'th', 'template-master-4', 'success_title', 'สำเร็จ'),
    (gen_random_uuid(), 'en', 'template-master-4', 'success_title', 'Success'),
    (gen_random_uuid(), 'th', 'template-master-4', 'ok_button', 'ตกลง'),
    (gen_random_uuid(), 'en', 'template-master-4', 'ok_button', 'OK');
