DELETE FROM nex_core.language_translations WHERE page_key = 'template-master-2';

INSERT INTO nex_core.language_translations (translation_id, language_code, page_key, label_key, label_value)
VALUES
    -- General & Search
    (gen_random_uuid(), 'th', 'template-master-2', 'title', 'หัวข้อ'),
    (gen_random_uuid(), 'en', 'template-master-2', 'title', 'Title'),
    (gen_random_uuid(), 'th', 'template-master-2', 'category', 'หมวดหมู่'),
    (gen_random_uuid(), 'en', 'template-master-2', 'category', 'Category'),
    (gen_random_uuid(), 'th', 'template-master-2', 'description', 'คำอธิบาย'),
    (gen_random_uuid(), 'en', 'template-master-2', 'description', 'Description'),
    (gen_random_uuid(), 'th', 'template-master-2', 'status', 'สถานะ'),
    (gen_random_uuid(), 'en', 'template-master-2', 'status', 'Status'),
    (gen_random_uuid(), 'th', 'template-master-2', 'all', 'ทั้งหมด'),
    (gen_random_uuid(), 'en', 'template-master-2', 'all', 'All'),
    (gen_random_uuid(), 'th', 'template-master-2', 'active', 'ใช้งาน'),
    (gen_random_uuid(), 'en', 'template-master-2', 'active', 'Active'),
    (gen_random_uuid(), 'th', 'template-master-2', 'inactive', 'ยกเลิก'),
    (gen_random_uuid(), 'en', 'template-master-2', 'inactive', 'Inactive'),
    (gen_random_uuid(), 'th', 'template-master-2', 'search_title', 'พิมพ์หัวข้อ...'),
    (gen_random_uuid(), 'en', 'template-master-2', 'search_title', 'Search title...'),
    (gen_random_uuid(), 'th', 'template-master-2', 'search_category', 'พิมพ์หมวดหมู่...'),
    (gen_random_uuid(), 'en', 'template-master-2', 'search_category', 'Search category...'),
    (gen_random_uuid(), 'th', 'template-master-2', 'search_desc', 'พิมพ์คำอธิบาย...'),
    (gen_random_uuid(), 'en', 'template-master-2', 'search_desc', 'Search description...'),
    (gen_random_uuid(), 'th', 'template-master-2', 'search_placeholder', 'ค้นหาตัวอย่าง...'),
    (gen_random_uuid(), 'en', 'template-master-2', 'search_placeholder', 'Search examples...'),
    
    -- Table Headers
    (gen_random_uuid(), 'th', 'template-master-2', 'template_id', 'ID'),
    (gen_random_uuid(), 'en', 'template-master-2', 'template_id', 'ID'),
    (gen_random_uuid(), 'th', 'template-master-2', 'template_name', 'หัวข้อ'),
    (gen_random_uuid(), 'en', 'template-master-2', 'template_name', 'Title'),
    (gen_random_uuid(), 'th', 'template-master-2', 'template_group', 'หมวดหมู่'),
    (gen_random_uuid(), 'en', 'template-master-2', 'template_group', 'Category'),
    (gen_random_uuid(), 'th', 'template-master-2', 'template_desc', 'อธิบายการใช้งาน'),
    (gen_random_uuid(), 'en', 'template-master-2', 'template_desc', 'Usage Description'),
    (gen_random_uuid(), 'th', 'template-master-2', 'is_active', 'สถานะ'),
    (gen_random_uuid(), 'en', 'template-master-2', 'is_active', 'Status'),
    (gen_random_uuid(), 'th', 'template-master-2', 'manage', 'จัดการ'),
    (gen_random_uuid(), 'en', 'template-master-2', 'manage', 'Manage'),

    -- Summary Cards
    (gen_random_uuid(), 'th', 'template-master-2', 'total_items', 'รายการทั้งหมด'),
    (gen_random_uuid(), 'en', 'template-master-2', 'total_items', 'Total Items'),
    (gen_random_uuid(), 'th', 'template-master-2', 'items', 'รายการ'),
    (gen_random_uuid(), 'en', 'template-master-2', 'items', 'Items'),

    -- Actions
    (gen_random_uuid(), 'th', 'template-master-2', 'add_data', 'เพิ่มข้อมูล'),
    (gen_random_uuid(), 'en', 'template-master-2', 'add_data', 'Add Data'),
    (gen_random_uuid(), 'th', 'template-master-2', 'view', 'เรียกดู'),
    (gen_random_uuid(), 'en', 'template-master-2', 'view', 'View'),
    (gen_random_uuid(), 'th', 'template-master-2', 'edit', 'แก้ไข'),
    (gen_random_uuid(), 'en', 'template-master-2', 'edit', 'Edit'),
    (gen_random_uuid(), 'th', 'template-master-2', 'delete', 'ลบ'),
    (gen_random_uuid(), 'en', 'template-master-2', 'delete', 'Delete'),
    (gen_random_uuid(), 'th', 'template-master-2', 'column_settings', 'ตั้งค่าคอลัมน์'),
    (gen_random_uuid(), 'en', 'template-master-2', 'column_settings', 'Column Settings'),
    (gen_random_uuid(), 'th', 'template-master-2', 'template_2_report', 'Template 2 Report'),
    (gen_random_uuid(), 'en', 'template-master-2', 'template_2_report', 'Template 2 Report'),

    -- Modals (CRUD)
    (gen_random_uuid(), 'th', 'template-master-2', 'add_new_data', 'เพิ่มข้อมูลใหม่'),
    (gen_random_uuid(), 'en', 'template-master-2', 'add_new_data', 'Add New Data'),
    (gen_random_uuid(), 'th', 'template-master-2', 'edit_data', 'แก้ไขข้อมูล'),
    (gen_random_uuid(), 'en', 'template-master-2', 'edit_data', 'Edit Data'),
    (gen_random_uuid(), 'th', 'template-master-2', 'view_data', 'รายละเอียดข้อมูล'),
    (gen_random_uuid(), 'en', 'template-master-2', 'view_data', 'Data Details'),
    (gen_random_uuid(), 'th', 'template-master-2', 'cancel', 'ยกเลิก'),
    (gen_random_uuid(), 'en', 'template-master-2', 'cancel', 'Cancel'),
    (gen_random_uuid(), 'th', 'template-master-2', 'save_data', 'บันทึกข้อมูล'),
    (gen_random_uuid(), 'en', 'template-master-2', 'save_data', 'Save Data'),
    (gen_random_uuid(), 'th', 'template-master-2', 'saving', 'กำลังบันทึก...'),
    (gen_random_uuid(), 'en', 'template-master-2', 'saving', 'Saving...'),
    (gen_random_uuid(), 'th', 'template-master-2', 'close', 'ปิด'),
    (gen_random_uuid(), 'en', 'template-master-2', 'close', 'Close'),

    -- Modal Inputs
    (gen_random_uuid(), 'th', 'template-master-2', 'enter_title', 'ระบุชื่อหัวข้อ'),
    (gen_random_uuid(), 'en', 'template-master-2', 'enter_title', 'Enter title'),
    (gen_random_uuid(), 'th', 'template-master-2', 'add_category', 'เพิ่มหมวดหมู่'),
    (gen_random_uuid(), 'en', 'template-master-2', 'add_category', 'Add Category'),
    (gen_random_uuid(), 'th', 'template-master-2', 'enter_desc', 'ระบุคำอธิบาย หรือหมายเหตุ'),
    (gen_random_uuid(), 'en', 'template-master-2', 'enter_desc', 'Enter description or remarks'),
    (gen_random_uuid(), 'th', 'template-master-2', 'usage_status', 'สถานะการใช้งาน'),
    (gen_random_uuid(), 'en', 'template-master-2', 'usage_status', 'Usage Status'),
    (gen_random_uuid(), 'th', 'template-master-2', 'read_only', '*(ดูอย่างเดียว)'),
    (gen_random_uuid(), 'en', 'template-master-2', 'read_only', '*(Read Only)'),

    -- Add Category Modal
    (gen_random_uuid(), 'th', 'template-master-2', 'add_new_category', 'เพิ่มหมวดหมู่ใหม่'),
    (gen_random_uuid(), 'en', 'template-master-2', 'add_new_category', 'Add New Category'),
    (gen_random_uuid(), 'th', 'template-master-2', 'category_name', 'ชื่อหมวดหมู่'),
    (gen_random_uuid(), 'en', 'template-master-2', 'category_name', 'Category Name'),
    (gen_random_uuid(), 'th', 'template-master-2', 'enter_category_name', 'ระบุชื่อหมวดหมู่'),
    (gen_random_uuid(), 'en', 'template-master-2', 'enter_category_name', 'Enter category name'),

    -- Delete Confirmation
    (gen_random_uuid(), 'th', 'template-master-2', 'confirm_delete_title', 'ยืนยันการลบข้อมูล'),
    (gen_random_uuid(), 'en', 'template-master-2', 'confirm_delete_title', 'Confirm Data Deletion'),
    (gen_random_uuid(), 'th', 'template-master-2', 'deleting', 'กำลังลบ...'),
    (gen_random_uuid(), 'en', 'template-master-2', 'deleting', 'Deleting...'),
    (gen_random_uuid(), 'th', 'template-master-2', 'delete_data', 'ลบข้อมูล'),
    (gen_random_uuid(), 'en', 'template-master-2', 'delete_data', 'Delete Data'),
    (gen_random_uuid(), 'th', 'template-master-2', 'delete_confirm_msg', 'คุณแน่ใจหรือไม่ว่าต้องการลบข้อมูล'),
    (gen_random_uuid(), 'en', 'template-master-2', 'delete_confirm_msg', 'Are you sure you want to delete data'),
    (gen_random_uuid(), 'th', 'template-master-2', 'cannot_undo', 'การกระทำนี้จะไม่สามารถย้อนกลับได้'),
    (gen_random_uuid(), 'en', 'template-master-2', 'cannot_undo', 'This action cannot be undone'),

    -- Column Settings
    (gen_random_uuid(), 'th', 'template-master-2', 'column_settings_title', 'ตั้งค่าการแสดงผลตาราง'),
    (gen_random_uuid(), 'en', 'template-master-2', 'column_settings_title', 'Table Display Settings'),
    (gen_random_uuid(), 'th', 'template-master-2', 'select_columns_to_show', 'เลือกคอลัมน์ที่ต้องการแสดง'),
    (gen_random_uuid(), 'en', 'template-master-2', 'select_columns_to_show', 'Select columns to display'),
    (gen_random_uuid(), 'th', 'template-master-2', 'sort_data', 'เรียงลำดับข้อมูล'),
    (gen_random_uuid(), 'en', 'template-master-2', 'sort_data', 'Sort Data'),
    (gen_random_uuid(), 'th', 'template-master-2', 'no_sort', 'ไม่เรียง'),
    (gen_random_uuid(), 'en', 'template-master-2', 'no_sort', 'No Sort'),
    (gen_random_uuid(), 'th', 'template-master-2', 'sort', 'เรียง'),
    (gen_random_uuid(), 'en', 'template-master-2', 'sort', 'Sort'),

    -- Feedback / Alert Messages
    (gen_random_uuid(), 'th', 'template-master-2', 'no_data_found', 'ไม่พบข้อมูล'),
    (gen_random_uuid(), 'en', 'template-master-2', 'no_data_found', 'No data found'),
    (gen_random_uuid(), 'th', 'template-master-2', 'require_template_name', 'กรุณาระบุชื่อข้อมูล'),
    (gen_random_uuid(), 'en', 'template-master-2', 'require_template_name', 'Please enter data name'),
    (gen_random_uuid(), 'th', 'template-master-2', 'save_success', 'บันทึกข้อมูลเรียบร้อยแล้ว'),
    (gen_random_uuid(), 'en', 'template-master-2', 'save_success', 'Data saved successfully'),
    (gen_random_uuid(), 'th', 'template-master-2', 'error_saving', 'เกิดข้อผิดพลาดในการบันทึกข้อมูล'),
    (gen_random_uuid(), 'en', 'template-master-2', 'error_saving', 'Error saving data'),
    (gen_random_uuid(), 'th', 'template-master-2', 'delete_success', 'ลบข้อมูลเรียบร้อยแล้ว'),
    (gen_random_uuid(), 'en', 'template-master-2', 'delete_success', 'Data deleted successfully'),
    (gen_random_uuid(), 'th', 'template-master-2', 'error_deleting', 'ลบข้อมูลไม่สำเร็จ'),
    (gen_random_uuid(), 'en', 'template-master-2', 'error_deleting', 'Error deleting data'),
    (gen_random_uuid(), 'th', 'template-master-2', 'error_changing_status', 'เปลี่ยนสถานะไม่สำเร็จ'),
    (gen_random_uuid(), 'en', 'template-master-2', 'error_changing_status', 'Error changing status'),
    (gen_random_uuid(), 'th', 'template-master-2', 'error_title', 'แจ้งเตือนข้อผิดพลาด'),
    (gen_random_uuid(), 'en', 'template-master-2', 'error_title', 'Error Notification'),
    (gen_random_uuid(), 'th', 'template-master-2', 'success_title', 'สำเร็จ'),
    (gen_random_uuid(), 'en', 'template-master-2', 'success_title', 'Success'),
    (gen_random_uuid(), 'th', 'template-master-2', 'ok_button', 'ตกลง'),
    (gen_random_uuid(), 'en', 'template-master-2', 'ok_button', 'OK');
