DELETE FROM nex_core.language_translations WHERE page_key = 'template-master-3';

INSERT INTO nex_core.language_translations (translation_id, language_code, page_key, label_key, label_value, is_active) VALUES 
-- th
(gen_random_uuid(), 'th', 'template-master-3', 'total_value', 'มูลค่ารวม', true),
(gen_random_uuid(), 'th', 'template-master-3', 'items', 'รายการ', true),
(gen_random_uuid(), 'th', 'template-master-3', 'import', 'Import', true),
(gen_random_uuid(), 'th', 'template-master-3', 'customer', 'ลูกค้า', true),
(gen_random_uuid(), 'th', 'template-master-3', 'search_customer', 'ชื่อลูกค้า...', true),
(gen_random_uuid(), 'th', 'template-master-3', 'product', 'สินค้า', true),
(gen_random_uuid(), 'th', 'template-master-3', 'search_product', 'ประเภทสินค้า...', true),
(gen_random_uuid(), 'th', 'template-master-3', 'origin', 'ต้นทาง', true),
(gen_random_uuid(), 'th', 'template-master-3', 'search_origin', 'ต้นทาง...', true),
(gen_random_uuid(), 'th', 'template-master-3', 'destination', 'ปลายทาง', true),
(gen_random_uuid(), 'th', 'template-master-3', 'search_destination', 'ปลายทาง...', true),
(gen_random_uuid(), 'th', 'template-master-3', 'status', 'สถานะ', true),
(gen_random_uuid(), 'th', 'template-master-3', 'all', 'ทั้งหมด', true),
(gen_random_uuid(), 'th', 'template-master-3', 'status_pending', 'รอจัดส่ง', true),
(gen_random_uuid(), 'th', 'template-master-3', 'status_in_transit', 'กำลังขนส่ง', true),
(gen_random_uuid(), 'th', 'template-master-3', 'status_completed', 'สำเร็จ', true),
(gen_random_uuid(), 'th', 'template-master-3', 'status_cancelled', 'ยกเลิก', true),
(gen_random_uuid(), 'th', 'template-master-3', 'priority', 'Priority', true),
(gen_random_uuid(), 'th', 'template-master-3', 'priority_normal', 'ปกติ', true),
(gen_random_uuid(), 'th', 'template-master-3', 'priority_urgent', 'เร่งด่วน', true),
(gen_random_uuid(), 'th', 'template-master-3', 'priority_express', 'ด่วนพิเศษ', true),
(gen_random_uuid(), 'th', 'template-master-3', 'order_id', 'รหัส Order', true),
(gen_random_uuid(), 'th', 'template-master-3', 'order_id_placeholder', 'เช่น ORD-051', true),
(gen_random_uuid(), 'th', 'template-master-3', 'customer_name', 'ชื่อลูกค้า', true),
(gen_random_uuid(), 'th', 'template-master-3', 'customer_name_placeholder', 'ชื่อบริษัท/ลูกค้า', true),
(gen_random_uuid(), 'th', 'template-master-3', 'cargo_type', 'ประเภทสินค้า', true),
(gen_random_uuid(), 'th', 'template-master-3', 'select', 'เลือก', true),
(gen_random_uuid(), 'th', 'template-master-3', 'select_origin', 'เลือกต้นทาง', true),
(gen_random_uuid(), 'th', 'template-master-3', 'select_destination', 'เลือกปลายทาง', true),
(gen_random_uuid(), 'th', 'template-master-3', 'weight', 'น้ำหนัก', true),
(gen_random_uuid(), 'th', 'template-master-3', 'ton', 'ตัน', true),
(gen_random_uuid(), 'th', 'template-master-3', 'delivery_date', 'วันส่ง', true),
(gen_random_uuid(), 'th', 'template-master-3', 'estimated_cost', 'ราคาประเมิน', true),
(gen_random_uuid(), 'th', 'template-master-3', 'baht', 'บาท', true),
(gen_random_uuid(), 'th', 'template-master-3', 'show', 'แสดง', true),
(gen_random_uuid(), 'th', 'template-master-3', 'records_per_page', 'รายการ / หน้า', true),
(gen_random_uuid(), 'th', 'template-master-3', 'from', 'จาก', true),
(gen_random_uuid(), 'th', 'template-master-3', 'search_placeholder', 'ค้นหาลูกค้า, Order...', true),
(gen_random_uuid(), 'th', 'template-master-3', 'list_view', 'List', true),
(gen_random_uuid(), 'th', 'template-master-3', 'grid_view', 'Grid', true),
(gen_random_uuid(), 'th', 'template-master-3', 'add_data', 'เพิ่มข้อมูล', true),
(gen_random_uuid(), 'th', 'template-master-3', 'select_all', 'เลือกทั้งหมด', true),
(gen_random_uuid(), 'th', 'template-master-3', 'route', 'ต้นทาง → ปลายทาง', true),
(gen_random_uuid(), 'th', 'template-master-3', 'view_order', 'รายละเอียดคำสั่งขนส่ง', true),
(gen_random_uuid(), 'th', 'template-master-3', 'add_order', 'เพิ่มคำสั่งขนส่ง', true),
(gen_random_uuid(), 'th', 'template-master-3', 'edit_order', 'แก้ไขคำสั่งขนส่ง', true),
(gen_random_uuid(), 'th', 'template-master-3', 'cancel', 'ยกเลิก', true),
(gen_random_uuid(), 'th', 'template-master-3', 'save_data', 'บันทึกข้อมูล', true),
(gen_random_uuid(), 'th', 'template-master-3', 'confirm_delete', 'ยืนยันการลบ', true),
(gen_random_uuid(), 'th', 'template-master-3', 'delete_confirm_msg', 'คุณต้องการลบคำสั่ง', true),
(gen_random_uuid(), 'th', 'template-master-3', 'of', 'ของ', true),
(gen_random_uuid(), 'th', 'template-master-3', 'question_mark', 'หรือไม่?', true),
(gen_random_uuid(), 'th', 'template-master-3', 'delete_data', 'ลบข้อมูล', true),
(gen_random_uuid(), 'th', 'template-master-3', 'form_incomplete', 'กรุณากรอกข้อมูลที่จำเป็นให้ครบถ้วน', true),
(gen_random_uuid(), 'th', 'template-master-3', 'save_success', 'บันทึกข้อมูลเรียบร้อยแล้ว', true),
(gen_random_uuid(), 'th', 'template-master-3', 'save_error', 'เกิดข้อผิดพลาดในการบันทึกข้อมูล', true),
(gen_random_uuid(), 'th', 'template-master-3', 'delete_success', 'ลบข้อมูลเรียบร้อยแล้ว', true),
(gen_random_uuid(), 'th', 'template-master-3', 'delete_error', 'เกิดข้อผิดพลาดในการลบข้อมูล', true),
(gen_random_uuid(), 'th', 'template-master-3', 'price', 'ราคา', true),
(gen_random_uuid(), 'th', 'template-master-3', 'req_order_id', 'กรุณาระบุรหัส', true),
(gen_random_uuid(), 'th', 'template-master-3', 'req_customer_name', 'กรุณาระบุชื่อลูกค้า', true),
(gen_random_uuid(), 'th', 'template-master-3', 'req_origin', 'กรุณาเลือกต้นทาง', true),
(gen_random_uuid(), 'th', 'template-master-3', 'req_destination', 'กรุณาเลือกปลายทาง', true),
(gen_random_uuid(), 'th', 'template-master-3', 'req_dest_diff_origin', 'ต้นทางและปลายทางต้องไม่ซ้ำกัน', true),
(gen_random_uuid(), 'th', 'template-master-3', 'req_delivery_date', 'กรุณาระบุวันส่ง', true),
-- en
(gen_random_uuid(), 'en', 'template-master-3', 'total_value', 'Total Value', true),
(gen_random_uuid(), 'en', 'template-master-3', 'items', 'Items', true),
(gen_random_uuid(), 'en', 'template-master-3', 'import', 'Import', true),
(gen_random_uuid(), 'en', 'template-master-3', 'customer', 'Customer', true),
(gen_random_uuid(), 'en', 'template-master-3', 'search_customer', 'Customer Name...', true),
(gen_random_uuid(), 'en', 'template-master-3', 'product', 'Product', true),
(gen_random_uuid(), 'en', 'template-master-3', 'search_product', 'Product Type...', true),
(gen_random_uuid(), 'en', 'template-master-3', 'origin', 'Origin', true),
(gen_random_uuid(), 'en', 'template-master-3', 'search_origin', 'Origin...', true),
(gen_random_uuid(), 'en', 'template-master-3', 'destination', 'Destination', true),
(gen_random_uuid(), 'en', 'template-master-3', 'search_destination', 'Destination...', true),
(gen_random_uuid(), 'en', 'template-master-3', 'status', 'Status', true),
(gen_random_uuid(), 'en', 'template-master-3', 'all', 'All', true),
(gen_random_uuid(), 'en', 'template-master-3', 'status_pending', 'Pending', true),
(gen_random_uuid(), 'en', 'template-master-3', 'status_in_transit', 'In Transit', true),
(gen_random_uuid(), 'en', 'template-master-3', 'status_completed', 'Completed', true),
(gen_random_uuid(), 'en', 'template-master-3', 'status_cancelled', 'Cancelled', true),
(gen_random_uuid(), 'en', 'template-master-3', 'priority', 'Priority', true),
(gen_random_uuid(), 'en', 'template-master-3', 'priority_normal', 'Normal', true),
(gen_random_uuid(), 'en', 'template-master-3', 'priority_urgent', 'Urgent', true),
(gen_random_uuid(), 'en', 'template-master-3', 'priority_express', 'Express', true),
(gen_random_uuid(), 'en', 'template-master-3', 'order_id', 'Order ID', true),
(gen_random_uuid(), 'en', 'template-master-3', 'order_id_placeholder', 'e.g. ORD-051', true),
(gen_random_uuid(), 'en', 'template-master-3', 'customer_name', 'Customer Name', true),
(gen_random_uuid(), 'en', 'template-master-3', 'customer_name_placeholder', 'Company/Customer Name', true),
(gen_random_uuid(), 'en', 'template-master-3', 'cargo_type', 'Cargo Type', true),
(gen_random_uuid(), 'en', 'template-master-3', 'select', 'Select', true),
(gen_random_uuid(), 'en', 'template-master-3', 'select_origin', 'Select Origin', true),
(gen_random_uuid(), 'en', 'template-master-3', 'select_destination', 'Select Destination', true),
(gen_random_uuid(), 'en', 'template-master-3', 'weight', 'Weight', true),
(gen_random_uuid(), 'en', 'template-master-3', 'ton', 'Ton', true),
(gen_random_uuid(), 'en', 'template-master-3', 'delivery_date', 'Delivery Date', true),
(gen_random_uuid(), 'en', 'template-master-3', 'estimated_cost', 'Estimated Cost', true),
(gen_random_uuid(), 'en', 'template-master-3', 'baht', 'Baht', true),
(gen_random_uuid(), 'en', 'template-master-3', 'show', 'Show', true),
(gen_random_uuid(), 'en', 'template-master-3', 'records_per_page', 'Records / Page', true),
(gen_random_uuid(), 'en', 'template-master-3', 'from', 'from', true),
(gen_random_uuid(), 'en', 'template-master-3', 'search_placeholder', 'Search Customer, Order...', true),
(gen_random_uuid(), 'en', 'template-master-3', 'list_view', 'List View', true),
(gen_random_uuid(), 'en', 'template-master-3', 'grid_view', 'Grid View', true),
(gen_random_uuid(), 'en', 'template-master-3', 'add_data', 'Add Data', true),
(gen_random_uuid(), 'en', 'template-master-3', 'select_all', 'Select All', true),
(gen_random_uuid(), 'en', 'template-master-3', 'route', 'Origin → Destination', true),
(gen_random_uuid(), 'en', 'template-master-3', 'view_order', 'Order Details', true),
(gen_random_uuid(), 'en', 'template-master-3', 'add_order', 'Add Order', true),
(gen_random_uuid(), 'en', 'template-master-3', 'edit_order', 'Edit Order', true),
(gen_random_uuid(), 'en', 'template-master-3', 'cancel', 'Cancel', true),
(gen_random_uuid(), 'en', 'template-master-3', 'save_data', 'Save Data', true),
(gen_random_uuid(), 'en', 'template-master-3', 'confirm_delete', 'Confirm Delete', true),
(gen_random_uuid(), 'en', 'template-master-3', 'delete_confirm_msg', 'Are you sure you want to delete order', true),
(gen_random_uuid(), 'en', 'template-master-3', 'of', 'of', true),
(gen_random_uuid(), 'en', 'template-master-3', 'question_mark', '?', true),
(gen_random_uuid(), 'en', 'template-master-3', 'delete_data', 'Delete Data', true),
(gen_random_uuid(), 'en', 'template-master-3', 'form_incomplete', 'Please fill in all required fields', true),
(gen_random_uuid(), 'en', 'template-master-3', 'save_success', 'Data saved successfully', true),
(gen_random_uuid(), 'en', 'template-master-3', 'save_error', 'Error saving data', true),
(gen_random_uuid(), 'en', 'template-master-3', 'delete_success', 'Data deleted successfully', true),
(gen_random_uuid(), 'en', 'template-master-3', 'delete_error', 'Error deleting data', true),
(gen_random_uuid(), 'en', 'template-master-3', 'price', 'Price', true),
(gen_random_uuid(), 'en', 'template-master-3', 'req_order_id', 'Please enter order ID', true),
(gen_random_uuid(), 'en', 'template-master-3', 'req_customer_name', 'Please enter customer name', true),
(gen_random_uuid(), 'en', 'template-master-3', 'req_origin', 'Please select origin', true),
(gen_random_uuid(), 'en', 'template-master-3', 'req_destination', 'Please select destination', true),
(gen_random_uuid(), 'en', 'template-master-3', 'req_dest_diff_origin', 'Origin and destination must not be the same', true),
(gen_random_uuid(), 'en', 'template-master-3', 'req_delivery_date', 'Please specify delivery date', true),
(gen_random_uuid(), 'th', 'template-master-3', 'manage', 'จัดการ', true),
(gen_random_uuid(), 'th', 'template-master-3', 'view', 'เรียกดู', true),
(gen_random_uuid(), 'th', 'template-master-3', 'edit', 'แก้ไข', true),
(gen_random_uuid(), 'th', 'template-master-3', 'delete', 'ลบ', true),
(gen_random_uuid(), 'th', 'template-master-3', 'no_data_found', 'ไม่พบข้อมูล', true),
(gen_random_uuid(), 'th', 'template-master-3', 'cargo_food', 'อาหาร', true),
(gen_random_uuid(), 'th', 'template-master-3', 'cargo_material', 'วัสดุก่อสร้าง', true),
(gen_random_uuid(), 'th', 'template-master-3', 'cargo_chemical', 'เคมีภัณฑ์', true),
(gen_random_uuid(), 'th', 'template-master-3', 'cargo_electronic', 'อุปกรณ์อิเล็กทรอนิกส์', true),
(gen_random_uuid(), 'th', 'template-master-3', 'cargo_general', 'สินค้าทั่วไป', true),
(gen_random_uuid(), 'th', 'template-master-3', 'cargo_oil', 'น้ำมัน', true),
(gen_random_uuid(), 'th', 'template-master-3', 'cargo_agri', 'สินค้าเกษตร', true),
(gen_random_uuid(), 'th', 'template-master-3', 'cargo_others', 'อื่นๆ', true),
(gen_random_uuid(), 'th', 'template-master-3', 'kg', 'กิโลกรัม', true),
(gen_random_uuid(), 'th', 'template-master-3', 'ok', 'ตกลง', true),
(gen_random_uuid(), 'th', 'template-master-3', 'error', 'ข้อผิดพลาด', true),
(gen_random_uuid(), 'th', 'template-master-3', 'success', 'สำเร็จ', true),
(gen_random_uuid(), 'th', 'template-master-3', 'deleting', 'กำลังลบ...', true),
(gen_random_uuid(), 'th', 'template-master-3', 'column_settings', 'ตั้งค่าคอลัมน์', true),
(gen_random_uuid(), 'th', 'template-master-3', 'column_settings_title', 'ตั้งค่าการแสดงผลตาราง', true),
(gen_random_uuid(), 'th', 'template-master-3', 'ok_button', 'ตกลง', true),
(gen_random_uuid(), 'th', 'template-master-3', 'no_sort', 'ไม่เรียง', true),
(gen_random_uuid(), 'th', 'template-master-3', 'sort', 'เรียง', true),
(gen_random_uuid(), 'th', 'template-master-3', 'sort_desc', 'เรียงจากมากไปน้อย', true),
(gen_random_uuid(), 'en', 'template-master-3', 'manage', 'Manage', true),
(gen_random_uuid(), 'en', 'template-master-3', 'view', 'View', true),
(gen_random_uuid(), 'en', 'template-master-3', 'edit', 'Edit', true),
(gen_random_uuid(), 'en', 'template-master-3', 'delete', 'Delete', true),
(gen_random_uuid(), 'en', 'template-master-3', 'no_data_found', 'No data found', true),
(gen_random_uuid(), 'en', 'template-master-3', 'cargo_food', 'Food', true),
(gen_random_uuid(), 'en', 'template-master-3', 'cargo_material', 'Construction Material', true),
(gen_random_uuid(), 'en', 'template-master-3', 'cargo_chemical', 'Chemicals', true),
(gen_random_uuid(), 'en', 'template-master-3', 'cargo_electronic', 'Electronics', true),
(gen_random_uuid(), 'en', 'template-master-3', 'cargo_general', 'General Cargo', true),
(gen_random_uuid(), 'en', 'template-master-3', 'cargo_oil', 'Oil', true),
(gen_random_uuid(), 'en', 'template-master-3', 'cargo_agri', 'Agricultural', true),
(gen_random_uuid(), 'en', 'template-master-3', 'cargo_others', 'Others', true),
(gen_random_uuid(), 'en', 'template-master-3', 'kg', 'kg', true),
(gen_random_uuid(), 'en', 'template-master-3', 'ok', 'OK', true),
(gen_random_uuid(), 'en', 'template-master-3', 'error', 'Error', true),
(gen_random_uuid(), 'en', 'template-master-3', 'success', 'Success', true),
(gen_random_uuid(), 'en', 'template-master-3', 'deleting', 'Deleting...', true),
(gen_random_uuid(), 'en', 'template-master-3', 'column_settings', 'Column Settings', true),
(gen_random_uuid(), 'en', 'template-master-3', 'column_settings_title', 'Table Display Settings', true),
(gen_random_uuid(), 'en', 'template-master-3', 'ok_button', 'OK', true),
(gen_random_uuid(), 'en', 'template-master-3', 'no_sort', 'No Sort', true),
(gen_random_uuid(), 'en', 'template-master-3', 'sort', 'Sort Ascending', true),
(gen_random_uuid(), 'en', 'template-master-3', 'sort_desc', 'Sort Descending', true);
