'use client';
import React, { useState, useEffect } from 'react';
import StatusDropdown from '@/components/StatusDropdown';
import { Search, Plus, Eye, Pencil, Trash2, X, ShoppingBag, Phone, MapPin, Star, ChevronLeft, ChevronRight, FileSpreadsheet, FileText, Download } from 'lucide-react';
import { api, PartsShop as APIPartsShop } from '@/services/api';

interface PartsShop { id: string; name: string; category: string; phone: string; address: string; rating: number; status: string; contactPerson: string; lineId: string; notes: string; }

const categories = ['อะไหล่เครื่องยนต์', 'อะไหล่ช่วงล่าง', 'อะไหล่ระบบเบรก', 'ยาง & ล้อ', 'ไฟ & ระบบไฟฟ้า', 'น้ำมัน & เคมีภัณฑ์', 'อะไหล่ตัวถัง', 'อะไหล่ทั่วไป'];
const statusLabels: Record<string, string> = { active: 'ใช้งาน', inactive: 'ปิดใช้งาน' };
const statusColors: Record<string, string> = { active: 'green', inactive: 'inactive' };

const emptyForm: Partial<PartsShop> = { name: '', category: 'อะไหล่ทั่วไป', phone: '', address: '', rating: 4.0, status: 'active', contactPerson: '', lineId: '', notes: '' };

export default function PartsShopsPage() {
    const [data, setData] = useState<PartsShop[]>([]);
    const [search, setSearch] = useState(''); const [currentPage, setCurrentPage] = useState(1);
    const [modal, setModal] = useState<'add' | 'edit' | 'view' | 'delete' | null>(null);
    const [selected, setSelected] = useState<PartsShop | null>(null);
    const [form, setForm] = useState<Partial<PartsShop>>(emptyForm);
    const perPage = 10;
    const loadData = async () => { try { const res = await api.getPartsShops(); setData((res || []).map(r => ({ ...r }) as PartsShop)); } catch { } };
    useEffect(() => { loadData(); }, []);
    const filtered = data.filter(r => !search || r.name.toLowerCase().includes(search.toLowerCase()) || r.category.includes(search) || r.id.toLowerCase().includes(search.toLowerCase()));
    const totalPages = Math.max(1, Math.ceil(filtered.length / perPage));
    const paged = filtered.slice((currentPage - 1) * perPage, currentPage * perPage);

    const handleSave = async () => { try { if (modal === 'add') { await api.createPartsShop({ ...form as APIPartsShop, id: `PTS-${String(data.length + 1).padStart(3, '0')}` }); } else if (modal === 'edit' && selected) { await api.updatePartsShop(selected.id, form as Partial<APIPartsShop>); } await loadData(); } catch { } setModal(null); };
    const handleDelete = async () => { if (selected) { try { await api.deletePartsShop(selected.id); await loadData(); } catch { } } setModal(null); };
    const exportCSV = () => { const rows = ['รหัส,ชื่อ,หมวดหมู่,โทร,ที่อยู่,ผู้ติดต่อ,Rating', ...filtered.map(r => `${r.id},${r.name},${r.category},${r.phone},${r.address},${r.contactPerson},${r.rating}`)].join('\n'); const b = new Blob(['\uFEFF' + rows], { type: 'text/csv;charset=utf-8' }); const u = URL.createObjectURL(b); const a = document.createElement('a'); a.href = u; a.download = 'parts_shops.csv'; a.click(); URL.revokeObjectURL(u); };
    const exportXLSX = async () => { const XLSX = await import('xlsx'); if (!filtered.length) { alert('ไม่มีข้อมูล'); return; } const wsData = [['รหัส', 'ชื่อร้าน', 'หมวดหมู่', 'โทร', 'ที่อยู่', 'ผู้ติดต่อ', 'Rating', 'สถานะ'], ...filtered.map(r => [r.id, r.name, r.category, r.phone, r.address, r.contactPerson, r.rating, statusLabels[r.status]])]; const ws = XLSX.utils.aoa_to_sheet(wsData); ws['!cols'] = [{ wch: 10 }, { wch: 20 }, { wch: 18 }, { wch: 14 }, { wch: 24 }, { wch: 14 }, { wch: 8 }, { wch: 12 }]; const wb = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(wb, ws, 'ร้านอะไหล่'); const wbout = XLSX.write(wb, { bookType: 'xlsx', type: 'array' }); const blob = new Blob([wbout], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' }); const u = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = u; a.download = `nexspeed_parts_shops_${new Date().toISOString().slice(0,10)}.xlsx`; a.click(); URL.revokeObjectURL(u); };
    const exportPDF = async () => { const { default: jsPDF } = await import('jspdf'); if (!filtered.length) { alert('ไม่มีข้อมูล'); return; } const doc = new jsPDF({ orientation: 'landscape' }); doc.setFontSize(16); doc.text('Parts Shops Report - NexSpeed', 14, 15); doc.setFontSize(10); doc.text(`Generated: ${new Date().toLocaleDateString('th-TH')}`, 14, 22); let y = 32; const headers = ['ID', 'Name', 'Category', 'Phone', 'Contact', 'Rating', 'Status']; const colX = [14, 35, 80, 125, 165, 210, 240]; doc.setFontSize(8); doc.setFont('helvetica', 'bold'); headers.forEach((h, i) => doc.text(h, colX[i], y)); doc.setFont('helvetica', 'normal'); y += 6; filtered.forEach(r => { if (y > 190) { doc.addPage(); y = 20; } const row = [r.id, r.name.substring(0, 20), r.category.substring(0, 18), r.phone, r.contactPerson.substring(0, 18), String(r.rating), r.status]; row.forEach((val, i) => doc.text(val, colX[i], y)); y += 5; }); const blob = doc.output('blob'); const u = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = u; a.download = `nexspeed_parts_shops_${new Date().toISOString().slice(0,10)}.pdf`; a.click(); URL.revokeObjectURL(u); };
    const eBtnStyle = (c: string): React.CSSProperties => ({ display: 'flex', alignItems: 'center', gap: '4px', padding: '6px 10px', background: 'transparent', border: `1.5px solid ${c}30`, borderRadius: '8px', color: c, fontSize: '12px', fontWeight: 600, cursor: 'pointer' });

    return (
        <div className="animate-fade-in">
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: '12px', marginBottom: '16px' }}>
                {[{ icon: <ShoppingBag size={22} />, color: '#3b82f6', label: 'ร้านทั้งหมด', value: String(data.length), sub: 'ร้าน', bg: 'rgba(59,130,246,0.07)' }, { icon: <ShoppingBag size={22} />, color: '#10b981', label: 'ใช้งาน', value: String(data.filter(r => r.status === 'active').length), sub: 'ร้าน', bg: 'rgba(16,185,129,0.07)' }, { icon: <Star size={22} />, color: '#f59e0b', label: 'Rating เฉลี่ย', value: (data.reduce((s, r) => s + r.rating, 0) / data.length).toFixed(1), sub: '⭐', bg: 'rgba(245,158,11,0.07)' }].map((card, i) => (
                    <div key={i} style={{ display: 'flex', alignItems: 'center', gap: '14px', padding: '16px 18px', borderRadius: '14px', background: card.bg, border: '1px solid transparent' }}><div style={{ width: '44px', height: '44px', borderRadius: '12px', background: `${card.color}18`, display: 'flex', alignItems: 'center', justifyContent: 'center', color: card.color }}>{card.icon}</div><div><div style={{ fontSize: '12px', color: 'var(--text-muted)', fontWeight: 500 }}>{card.label}</div><div style={{ display: 'flex', alignItems: 'baseline', gap: '4px' }}><span style={{ fontSize: '22px', fontWeight: 700, color: card.color }}>{card.value}</span><span style={{ fontSize: '12px', color: 'var(--text-muted)' }}>{card.sub}</span></div></div></div>
                ))}
            </div>
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '10px', flexWrap: 'wrap' }}>
                <button onClick={exportXLSX} style={eBtnStyle('#10b981')}><FileSpreadsheet size={14} /> XLSX</button><button onClick={exportCSV} style={eBtnStyle('#10b981')}><FileText size={14} /> CSV</button><button onClick={exportPDF} style={eBtnStyle('#ef4444')}><Download size={14} /> PDF</button><div style={{ flex: 1 }} />
                <div className="topbar-search" style={{ minWidth: '180px' }}><Search size={16} /><input placeholder="ค้นหาร้าน..." value={search} onChange={e => { setSearch(e.target.value); setCurrentPage(1); }} /></div>
                <button onClick={() => { setForm(emptyForm); setModal('add'); }} style={{ display: 'flex', alignItems: 'center', gap: '6px', padding: '8px 16px', borderRadius: '10px', border: 'none', background: 'var(--accent-blue)', color: 'white', fontSize: '13px', fontWeight: 600, fontFamily: 'inherit', cursor: 'pointer' }}><Plus size={16} /> เพิ่มร้าน</button>
            </div>
            <div className="card" style={{ padding: 0, overflow: 'hidden' }}><div style={{ overflowX: 'auto' }}><table className="data-table"><thead><tr><th>รหัส</th><th>ชื่อร้าน</th><th>หมวดหมู่</th><th>โทร</th><th>ผู้ติดต่อ</th><th>Rating</th><th>สถานะ</th><th style={{ textAlign: 'center', width: '110px' }}>จัดการ</th></tr></thead>
                <tbody>{paged.map(r => (<tr key={r.id}><td><span style={{ fontWeight: 700, color: 'var(--accent-blue)' }}>{r.id}</span></td><td>{r.name}</td><td>{r.category}</td><td><div style={{ display: 'flex', alignItems: 'center', gap: '4px' }}><Phone size={12} />{r.phone}</div></td><td>{r.contactPerson}</td><td>⭐ {r.rating}</td><td><StatusDropdown 
                    value={r.status}
                    onChange={async (newValue: any) => {
                        setData(prev => prev.map(x => x.id === r.id ? { ...x, status: newValue } : x));
                        try { await api.updatePartsShop(r.id, { ...r, status: newValue } as any); } catch(err) { console.error(err); }
                    }}
                    options={Object.keys(statusLabels).map(k => ({ 
                        value: k, 
                        label: statusLabels[k as keyof typeof statusLabels], 
                        color: (['active','completed','available', 'approved'].includes(k) ? 'green' : (['inactive','cancelled', 'rejected'].includes(k) ? 'red' : 'yellow')) as any
                    }))}
                /></td><td style={{ textAlign: 'center' }}><div style={{ display: 'flex', gap: '4px', justifyContent: 'center' }}><button className="btn-icon btn-icon-view" onClick={() => { setSelected(r); setModal('view'); }}><Eye size={14} /></button><button className="btn-icon btn-icon-edit" onClick={() => { setForm({ ...r }); setSelected(r); setModal('edit'); }}><Pencil size={14} /></button><button className="btn-icon btn-icon-delete" onClick={() => { setSelected(r); setModal('delete'); }}><Trash2 size={14} /></button></div></td></tr>))}{paged.length === 0 && <tr><td colSpan={8} style={{ textAlign: 'center', padding: '40px', color: 'var(--text-muted)' }}>ไม่พบรายการ</td></tr>}</tbody></table></div>
                {totalPages > 1 && <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '12px 16px', borderTop: '1px solid var(--border-color)' }}><span style={{ fontSize: '13px', color: 'var(--text-muted)' }}>แสดง {(currentPage - 1) * perPage + 1}-{Math.min(currentPage * perPage, filtered.length)} จาก {filtered.length}</span><div style={{ display: 'flex', gap: '4px' }}><button className="btn" disabled={currentPage === 1} onClick={() => setCurrentPage(p => p - 1)} style={{ padding: '6px 10px' }}><ChevronLeft size={14} /></button>{Array.from({ length: Math.min(totalPages, 5) }, (_, i) => i + 1).map(p => <button key={p} className={`btn ${currentPage === p ? 'btn-primary' : ''}`} onClick={() => setCurrentPage(p)} style={{ padding: '6px 12px', minWidth: '36px' }}>{p}</button>)}<button className="btn" disabled={currentPage === totalPages} onClick={() => setCurrentPage(p => p + 1)} style={{ padding: '6px 10px' }}><ChevronRight size={14} /></button></div></div>}</div>
            {modal && <div className="modal-backdrop" onClick={() => setModal(null)}><div className="modal" onClick={e => e.stopPropagation()} style={{ maxWidth: modal === 'delete' ? '400px' : '560px' }}>
                {modal === 'delete' && selected && <><div className="modal-header"><h3 className="modal-title" style={{ color: 'var(--accent-red)' }}>⚠️ ยืนยันลบ</h3><button className="modal-close" onClick={() => setModal(null)}><X size={18} /></button></div><div className="modal-body"><p>ต้องการลบ <strong>{selected.name}</strong>?</p></div><div className="modal-footer"><button className="btn" onClick={() => setModal(null)} style={{ padding: '8px 16px', background: '#ef4444', color: 'white', border: 'none', borderRadius: '8px', cursor: 'pointer', fontWeight: 500 }}>ยกเลิก</button><button className="btn btn-danger" onClick={handleDelete}>ลบ</button></div></>}
                {modal === 'view' && selected && <><div className="modal-header"><h3 className="modal-title">🏪 {selected.name}</h3><button className="modal-close" onClick={() => setModal(null)}><X size={18} /></button></div><div className="modal-body" style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '12px' }}>{[['รหัส', selected.id], ['ชื่อร้าน', selected.name], ['หมวดหมู่', selected.category], ['โทร', selected.phone], ['ผู้ติดต่อ', selected.contactPerson], ['Line ID', selected.lineId || '-'], ['ที่อยู่', selected.address], ['Rating', `${selected.rating} ⭐`]].map(([l, v], i) => <div key={i} style={{ padding: '10px', background: 'rgba(255,255,255,0.03)', borderRadius: '8px', border: '1px solid var(--border-color)' }}><div style={{ fontSize: '11px', color: 'var(--text-muted)', marginBottom: '4px' }}>{l}</div><div style={{ fontSize: '14px', fontWeight: 600 }}>{v}</div></div>)}</div><div className="modal-footer"><button className="btn" onClick={() => setModal(null)}>ปิด</button></div></>}
                {(modal === 'add' || modal === 'edit') && <><div className="modal-header"><h3 className="modal-title">{modal === 'add' ? '➕ เพิ่มร้านอะไหล่' : '✏️ แก้ไข'}</h3><button className="modal-close" onClick={() => setModal(null)}><X size={18} /></button></div><div className="modal-body" style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '14px' }}><div style={{ gridColumn: 'span 2' }}><label style={lbl}>ชื่อร้าน</label><input className="form-input" value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} style={{ width: '100%' }} /></div><div><label style={lbl}>หมวดหมู่</label><select className="form-input" value={form.category} onChange={e => setForm({ ...form, category: e.target.value })} style={{ width: '100%' }}>{categories.map(s => <option key={s} value={s}>{s}</option>)}</select></div><div><label style={lbl}>โทร</label><input className="form-input" value={form.phone} onChange={e => setForm({ ...form, phone: e.target.value })} style={{ width: '100%' }} /></div><div><label style={lbl}>ผู้ติดต่อ</label><input className="form-input" value={form.contactPerson} onChange={e => setForm({ ...form, contactPerson: e.target.value })} style={{ width: '100%' }} /></div><div><label style={lbl}>สถานะ</label><select className="form-input" value={form.status} onChange={e => setForm({ ...form, status: e.target.value })} style={{ width: '100%' }}>{Object.entries(statusLabels).map(([k, v]) => <option key={k} value={k}>{v}</option>)}</select></div><div style={{ gridColumn: 'span 2' }}><label style={lbl}>ที่อยู่</label><input className="form-input" value={form.address} onChange={e => setForm({ ...form, address: e.target.value })} style={{ width: '100%' }} /></div></div><div className="modal-footer"><button className="btn" onClick={() => setModal(null)} style={{ padding: '8px 16px', background: '#ef4444', color: 'white', border: 'none', borderRadius: '8px', cursor: 'pointer', fontWeight: 500 }}>ยกเลิก</button><button className="btn btn-primary" onClick={handleSave} style={{ padding: '8px 16px', background: 'var(--accent-green)', color: 'white', border: 'none', borderRadius: '8px', cursor: 'pointer', fontWeight: 500 }}>{modal === 'add' ? 'เพิ่มข้อมูล' : 'บันทึกข้อมูล'}</button></div></>}
            </div></div>}
        </div>
    );
}
const lbl: React.CSSProperties = { display: 'block', fontSize: '12px', fontWeight: 600, color: 'var(--text-muted)', marginBottom: '6px' };
