'use client';
import React, { useState, useEffect } from 'react';
import StatusDropdown from '@/components/StatusDropdown';
import { Search, Plus, Eye, Pencil, Trash2, X, Fuel, AlertTriangle, ChevronLeft, ChevronRight, FileSpreadsheet, FileText, Download } from 'lucide-react';
import { api, StockOil } from '@/services/api';

interface OilStock { id: string; name: string; type: string; brand: string; quantity: number; minStock: number; unit: string; unitPrice: number; location: string; supplier: string; expiryDate: string; status: string; }

const oilTypes = ['น้ำมันเครื่อง', 'น้ำมันเกียร์', 'น้ำมันเบรก', 'น้ำมันพวงมาลัย', 'น้ำมันไฮดรอลิก', 'จาระบี', 'น้ำยาหม้อน้ำ', 'น้ำมันหล่อลื่นทั่วไป'];
const statusLabels: Record<string, string> = { 'in-stock': 'มีสต๊อก', 'low-stock': '⚠️ ใกล้หมด', 'out-of-stock': '❌ หมด' };
const statusColors: Record<string, string> = { 'in-stock': 'green', 'low-stock': 'warning', 'out-of-stock': 'red' };

const emptyForm: Partial<OilStock> = { name: '', type: 'น้ำมันเครื่อง', brand: '', quantity: 0, minStock: 10, unit: 'ลิตร', unitPrice: 0, location: '', supplier: '', expiryDate: '', status: 'in-stock' };

export default function StockOilPage() {
    const [data, setData] = useState<OilStock[]>([]);
    const [search, setSearch] = useState(''); const [currentPage, setCurrentPage] = useState(1);
    const [modal, setModal] = useState<'add' | 'edit' | 'view' | 'delete' | null>(null);
    const [selected, setSelected] = useState<OilStock | null>(null);
    const [form, setForm] = useState<Partial<OilStock>>(emptyForm);
    const perPage = 10;
    const loadData = async () => { try { const res = await api.getStockOil(); setData((res || []).map(r => ({ ...r, expiryDate: r.expiryDate || '' }) as OilStock)); } catch { } };
    useEffect(() => { loadData(); }, []);
    const filtered = data.filter(r => !search || r.name.toLowerCase().includes(search.toLowerCase()) || r.brand.toLowerCase().includes(search.toLowerCase()) || r.id.toLowerCase().includes(search.toLowerCase()));
    const totalPages = Math.max(1, Math.ceil(filtered.length / perPage));
    const paged = filtered.slice((currentPage - 1) * perPage, currentPage * perPage);
    const totalValue = data.reduce((s, r) => s + r.quantity * r.unitPrice, 0);

    const handleSave = async () => { try { if (modal === 'add') { await api.createStockOil({ ...form as StockOil, id: `OIL-${String(data.length + 1).padStart(3, '0')}` }); } else if (modal === 'edit' && selected) { await api.updateStockOil(selected.id, form as Partial<StockOil>); } await loadData(); } catch { } setModal(null); };
    const handleDelete = async () => { if (selected) { try { await api.deleteStockOil(selected.id); await loadData(); } catch { } } setModal(null); };
    const exportCSV = () => { const rows = ['รหัส,ชื่อ,ประเภท,ยี่ห้อ,จำนวน,หน่วย,ราคา,ที่เก็บ', ...filtered.map(r => `${r.id},${r.name},${r.type},${r.brand},${r.quantity},${r.unit},${r.unitPrice},${r.location}`)].join('\n'); const b = new Blob(['\uFEFF' + rows], { type: 'text/csv;charset=utf-8' }); const u = URL.createObjectURL(b); const a = document.createElement('a'); a.href = u; a.download = 'stock_oil.csv'; a.click(); URL.revokeObjectURL(u); };
    const exportXLSX = async () => { const XLSX = await import('xlsx'); if (!filtered.length) { alert('ไม่มีข้อมูล'); return; } const wsData = [['รหัส', 'ชื่อ', 'ประเภท', 'ยี่ห้อ', 'จำนวน', 'หน่วย', 'ราคา/หน่วย', 'ที่เก็บ', 'สถานะ'], ...filtered.map(r => [r.id, r.name, r.type, r.brand, r.quantity, r.unit, r.unitPrice, r.location, statusLabels[r.status]])]; const ws = XLSX.utils.aoa_to_sheet(wsData); ws['!cols'] = [{ wch: 10 }, { wch: 20 }, { wch: 16 }, { wch: 14 }, { wch: 8 }, { wch: 8 }, { wch: 12 }, { wch: 14 }, { wch: 12 }]; const wb = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(wb, ws, 'สต๊อกน้ำมัน'); const wbout = XLSX.write(wb, { bookType: 'xlsx', type: 'array' }); const blob = new Blob([wbout], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' }); const u = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = u; a.download = `nexspeed_stock_oil_${new Date().toISOString().slice(0,10)}.xlsx`; a.click(); URL.revokeObjectURL(u); };
    const exportPDF = async () => { const { default: jsPDF } = await import('jspdf'); if (!filtered.length) { alert('ไม่มีข้อมูล'); return; } const doc = new jsPDF({ orientation: 'landscape' }); doc.setFontSize(16); doc.text('Stock Oil Report - NexSpeed', 14, 15); doc.setFontSize(10); doc.text(`Generated: ${new Date().toLocaleDateString('th-TH')}`, 14, 22); let y = 32; const headers = ['ID', 'Name', 'Type', 'Brand', 'Qty', 'Unit', 'Price', 'Location', 'Status']; const colX = [14, 30, 75, 115, 150, 170, 190, 220, 255]; doc.setFontSize(8); doc.setFont('helvetica', 'bold'); headers.forEach((h, i) => doc.text(h, colX[i], y)); doc.setFont('helvetica', 'normal'); y += 6; filtered.forEach(r => { if (y > 190) { doc.addPage(); y = 20; } const row = [r.id, r.name.substring(0, 20), r.type.substring(0, 16), r.brand, String(r.quantity), r.unit, String(r.unitPrice), r.location.substring(0, 14), r.status]; row.forEach((val, i) => doc.text(val, colX[i], y)); y += 5; }); const blob = doc.output('blob'); const u = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = u; a.download = `nexspeed_stock_oil_${new Date().toISOString().slice(0,10)}.pdf`; a.click(); URL.revokeObjectURL(u); };
    const eBtnStyle = (c: string): React.CSSProperties => ({ display: 'flex', alignItems: 'center', gap: '4px', padding: '6px 10px', background: 'transparent', border: `1.5px solid ${c}30`, borderRadius: '8px', color: c, fontSize: '12px', fontWeight: 600, cursor: 'pointer' });

    return (
        <div className="animate-fade-in">
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: '12px', marginBottom: '16px' }}>
                {[{ icon: <Fuel size={22} />, color: '#3b82f6', label: 'รายการทั้งหมด', value: String(data.length), sub: 'รายการ', bg: 'rgba(59,130,246,0.07)' }, { icon: <Fuel size={22} />, color: '#10b981', label: 'มีสต๊อก', value: String(data.filter(r => r.status === 'in-stock').length), sub: 'รายการ', bg: 'rgba(16,185,129,0.07)' }, { icon: <AlertTriangle size={22} />, color: '#f59e0b', label: 'ใกล้หมด', value: String(data.filter(r => r.status === 'low-stock').length), sub: 'รายการ', bg: 'rgba(245,158,11,0.07)' }, { icon: <Fuel size={22} />, color: '#8b5cf6', label: 'มูลค่ารวม', value: `฿${totalValue.toLocaleString()}`, sub: '', bg: 'rgba(139,92,246,0.07)' }].map((card, i) => (
                    <div key={i} style={{ display: 'flex', alignItems: 'center', gap: '14px', padding: '16px 18px', borderRadius: '14px', background: card.bg, border: '1px solid transparent' }}><div style={{ width: '44px', height: '44px', borderRadius: '12px', background: `${card.color}18`, display: 'flex', alignItems: 'center', justifyContent: 'center', color: card.color }}>{card.icon}</div><div><div style={{ fontSize: '12px', color: 'var(--text-muted)', fontWeight: 500 }}>{card.label}</div><div style={{ display: 'flex', alignItems: 'baseline', gap: '4px' }}><span style={{ fontSize: '22px', fontWeight: 700, color: card.color }}>{card.value}</span>{card.sub && <span style={{ fontSize: '12px', color: 'var(--text-muted)' }}>{card.sub}</span>}</div></div></div>
                ))}
            </div>
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '10px', flexWrap: 'wrap' }}>
                <button onClick={exportXLSX} style={eBtnStyle('#10b981')}><FileSpreadsheet size={14} /> XLSX</button><button onClick={exportCSV} style={eBtnStyle('#10b981')}><FileText size={14} /> CSV</button><button onClick={exportPDF} style={eBtnStyle('#ef4444')}><Download size={14} /> PDF</button><div style={{ flex: 1 }} />
                <div className="topbar-search" style={{ minWidth: '180px' }}><Search size={16} /><input placeholder="ค้นหาน้ำมัน, ยี่ห้อ..." value={search} onChange={e => { setSearch(e.target.value); setCurrentPage(1); }} /></div>
                <button onClick={() => { setForm(emptyForm); setModal('add'); }} style={{ display: 'flex', alignItems: 'center', gap: '6px', padding: '8px 16px', borderRadius: '10px', border: 'none', background: 'var(--accent-blue)', color: 'white', fontSize: '13px', fontWeight: 600, fontFamily: 'inherit', cursor: 'pointer' }}><Plus size={16} /> เพิ่มรายการ</button>
            </div>
            <div className="card" style={{ padding: 0, overflow: 'hidden' }}><div style={{ overflowX: 'auto' }}><table className="data-table"><thead><tr><th>รหัส</th><th>ชื่อ</th><th>ประเภท</th><th>ยี่ห้อ</th><th>จำนวน</th><th>ราคา/หน่วย</th><th>สถานะ</th><th style={{ textAlign: 'center', width: '110px' }}>จัดการ</th></tr></thead>
                <tbody>{paged.map(r => (<tr key={r.id}><td><span style={{ fontWeight: 700, color: 'var(--accent-blue)' }}>{r.id}</span></td><td>{r.name}</td><td>{r.type}</td><td>{r.brand}</td><td><span style={{ fontWeight: 600, color: r.quantity <= r.minStock ? 'var(--accent-red)' : 'inherit' }}>{r.quantity} {r.unit}</span></td><td>฿{r.unitPrice.toLocaleString()}</td><td><StatusDropdown 
                    value={r.status}
                    onChange={async (newValue: any) => {
                        setData(prev => prev.map(x => x.id === r.id ? { ...x, status: newValue } : x));
                        try { await api.updateStockOil(r.id, { ...r, status: newValue } as any); } catch(err) { console.error(err); }
                    }}
                    options={Object.keys(statusLabels).map(k => ({ 
                        value: k, 
                        label: statusLabels[k as keyof typeof statusLabels], 
                        color: (['active','completed','available', 'approved'].includes(k) ? 'green' : (['inactive','cancelled', 'rejected'].includes(k) ? 'red' : 'yellow')) as any
                    }))}
                /></td><td style={{ textAlign: 'center' }}><div style={{ display: 'flex', gap: '4px', justifyContent: 'center' }}><button className="btn-icon btn-icon-view" onClick={() => { setSelected(r); setModal('view'); }}><Eye size={14} /></button><button className="btn-icon btn-icon-edit" onClick={() => { setForm({ ...r }); setSelected(r); setModal('edit'); }}><Pencil size={14} /></button><button className="btn-icon btn-icon-delete" onClick={() => { setSelected(r); setModal('delete'); }}><Trash2 size={14} /></button></div></td></tr>))}{paged.length === 0 && <tr><td colSpan={8} style={{ textAlign: 'center', padding: '40px', color: 'var(--text-muted)' }}>ไม่พบรายการ</td></tr>}</tbody></table></div>
                {totalPages > 1 && <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '12px 16px', borderTop: '1px solid var(--border-color)' }}><span style={{ fontSize: '13px', color: 'var(--text-muted)' }}>แสดง {(currentPage - 1) * perPage + 1}-{Math.min(currentPage * perPage, filtered.length)} จาก {filtered.length}</span><div style={{ display: 'flex', gap: '4px' }}><button className="btn" disabled={currentPage === 1} onClick={() => setCurrentPage(p => p - 1)} style={{ padding: '6px 10px' }}><ChevronLeft size={14} /></button>{Array.from({ length: Math.min(totalPages, 5) }, (_, i) => i + 1).map(p => <button key={p} className={`btn ${currentPage === p ? 'btn-primary' : ''}`} onClick={() => setCurrentPage(p)} style={{ padding: '6px 12px', minWidth: '36px' }}>{p}</button>)}<button className="btn" disabled={currentPage === totalPages} onClick={() => setCurrentPage(p => p + 1)} style={{ padding: '6px 10px' }}><ChevronRight size={14} /></button></div></div>}</div>
            {modal && <div className="modal-backdrop" onClick={() => setModal(null)}><div className="modal" onClick={e => e.stopPropagation()} style={{ maxWidth: modal === 'delete' ? '400px' : '560px' }}>
                {modal === 'delete' && selected && <><div className="modal-header"><h3 className="modal-title" style={{ color: 'var(--accent-red)' }}>⚠️ ยืนยันลบ</h3><button className="modal-close" onClick={() => setModal(null)}><X size={18} /></button></div><div className="modal-body"><p>ต้องการลบ <strong>{selected.name}</strong>?</p></div><div className="modal-footer"><button className="btn" onClick={() => setModal(null)} style={{ padding: '8px 16px', background: '#ef4444', color: 'white', border: 'none', borderRadius: '8px', cursor: 'pointer', fontWeight: 500 }}>ยกเลิก</button><button className="btn btn-danger" onClick={handleDelete}>ลบ</button></div></>}
                {modal === 'view' && selected && <><div className="modal-header"><h3 className="modal-title">🛢️ {selected.name}</h3><button className="modal-close" onClick={() => setModal(null)}><X size={18} /></button></div><div className="modal-body" style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '12px' }}>{[['รหัส', selected.id], ['ชื่อ', selected.name], ['ประเภท', selected.type], ['ยี่ห้อ', selected.brand], ['จำนวน', `${selected.quantity} ${selected.unit}`], ['Min Stock', `${selected.minStock} ${selected.unit}`], ['ราคา/หน่วย', `฿${selected.unitPrice.toLocaleString()}`], ['มูลค่ารวม', `฿${(selected.quantity * selected.unitPrice).toLocaleString()}`], ['ที่เก็บ', selected.location], ['วันหมดอายุ', selected.expiryDate]].map(([l, v], i) => <div key={i} style={{ padding: '10px', background: 'rgba(255,255,255,0.03)', borderRadius: '8px', border: '1px solid var(--border-color)' }}><div style={{ fontSize: '11px', color: 'var(--text-muted)', marginBottom: '4px' }}>{l}</div><div style={{ fontSize: '14px', fontWeight: 600 }}>{v}</div></div>)}</div><div className="modal-footer"><button className="btn" onClick={() => setModal(null)}>ปิด</button></div></>}
                {(modal === 'add' || modal === 'edit') && <><div className="modal-header"><h3 className="modal-title">{modal === 'add' ? '➕ เพิ่มน้ำมัน' : '✏️ แก้ไข'}</h3><button className="modal-close" onClick={() => setModal(null)}><X size={18} /></button></div><div className="modal-body" style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '14px' }}><div style={{ gridColumn: 'span 2' }}><label style={lbl}>ชื่อ</label><input className="form-input" value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} style={{ width: '100%' }} /></div><div><label style={lbl}>ประเภท</label><select className="form-input" value={form.type} onChange={e => setForm({ ...form, type: e.target.value })} style={{ width: '100%' }}>{oilTypes.map(s => <option key={s} value={s}>{s}</option>)}</select></div><div><label style={lbl}>ยี่ห้อ</label><input className="form-input" value={form.brand} onChange={e => setForm({ ...form, brand: e.target.value })} style={{ width: '100%' }} /></div><div><label style={lbl}>จำนวน</label><input className="form-input" type="number" value={form.quantity} onChange={e => setForm({ ...form, quantity: +e.target.value })} style={{ width: '100%' }} /></div><div><label style={lbl}>ราคา/หน่วย</label><input className="form-input" type="number" value={form.unitPrice} onChange={e => setForm({ ...form, unitPrice: +e.target.value })} style={{ width: '100%' }} /></div><div><label style={lbl}>ที่เก็บ</label><input className="form-input" value={form.location} onChange={e => setForm({ ...form, location: e.target.value })} style={{ width: '100%' }} /></div><div><label style={lbl}>วันหมดอายุ</label><input className="form-input" type="date" value={form.expiryDate} onChange={e => setForm({ ...form, expiryDate: e.target.value })} style={{ width: '100%' }} /></div></div><div className="modal-footer"><button className="btn" onClick={() => setModal(null)} style={{ padding: '8px 16px', background: '#ef4444', color: 'white', border: 'none', borderRadius: '8px', cursor: 'pointer', fontWeight: 500 }}>ยกเลิก</button><button className="btn btn-primary" onClick={handleSave} style={{ padding: '8px 16px', background: 'var(--accent-green)', color: 'white', border: 'none', borderRadius: '8px', cursor: 'pointer', fontWeight: 500 }}>{modal === 'add' ? 'เพิ่มข้อมูล' : 'บันทึกข้อมูล'}</button></div></>}
            </div></div>}
        </div>
    );
}
const lbl: React.CSSProperties = { display: 'block', fontSize: '12px', fontWeight: 600, color: 'var(--text-muted)', marginBottom: '6px' };
