-- Employee Dashboard Page Translations (page_key = 'employee')
-- Path: /dashboard/employee → derivePageKey() => 'employee'
-- This script inserts Thai (th) and English (en) translations for all labels.

-- ═══════════════════════════════════════════════════════════════════
-- Thai (th) translations
-- ═══════════════════════════════════════════════════════════════════

-- Welcome & Profile
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee', 'Loading dashboard...', 'กำลังโหลดแดชบอร์ด...', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee' AND label_key='Loading dashboard...');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee', 'Welcome Back', 'ยินดีต้อนรับกลับ', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee' AND label_key='Welcome Back');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee', 'View Profile', 'ดูโปรไฟล์', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee' AND label_key='View Profile');

-- Timesheet / Check-in
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee', 'Timesheet', 'บันทึกเวลา', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee' AND label_key='Timesheet');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee', 'Today', 'วันนี้', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee' AND label_key='Today');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee', 'Check In', 'เข้างาน', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee' AND label_key='Check In');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee', 'Check Out', 'ออกงาน', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee' AND label_key='Check Out');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee', 'Punch In', 'ลงเวลาเข้า', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee' AND label_key='Punch In');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee', 'Punch Out', 'ลงเวลาออก', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee' AND label_key='Punch Out');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee', 'Punch Completed', 'ลงเวลาครบแล้ว', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee' AND label_key='Punch Completed');

-- Work stats
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee', 'Production', 'ชั่วโมงทำงาน', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee' AND label_key='Production');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee', 'Overtime', 'ล่วงเวลา', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee' AND label_key='Overtime');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee', 'Break', 'พัก', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee' AND label_key='Break');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee', 'Hrs', 'ชม.', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee' AND label_key='Hrs');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee', 'Min', 'นาที', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee' AND label_key='Min');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee', 'View Attendance', 'ดูการเข้างาน', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee' AND label_key='View Attendance');

-- Holidays
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee', 'Upcoming Holidays', 'วันหยุดที่จะถึง', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee' AND label_key='Upcoming Holidays');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee', 'View All', 'ดูทั้งหมด', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee' AND label_key='View All');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee', 'No upcoming holidays', 'ไม่มีวันหยุดที่จะถึง', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee' AND label_key='No upcoming holidays');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee', 'Holidays', 'วันหยุด', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee' AND label_key='Holidays');

-- Attendance & Leaves
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee', 'Attendance & Leaves', 'การเข้างานและการลา', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee' AND label_key='Attendance & Leaves');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee', 'Total Leaves', 'วันลาทั้งหมด', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee' AND label_key='Total Leaves');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee', 'Leaves Taken', 'ลาไปแล้ว', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee' AND label_key='Leaves Taken');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee', 'Available', 'คงเหลือ', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee' AND label_key='Available');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee', 'Pending', 'รออนุมัติ', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee' AND label_key='Pending');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee', 'Approved', 'อนุมัติแล้ว', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee' AND label_key='Approved');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee', 'Rejected', 'ปฏิเสธ', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee' AND label_key='Rejected');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee', 'Apply Leave', 'ยื่นลา', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee' AND label_key='Apply Leave');

-- Leave Balance
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee', 'Leave Balance', 'ยอดวันลาคงเหลือ', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee' AND label_key='Leave Balance');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee', 'No leave data', 'ไม่มีข้อมูลการลา', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee' AND label_key='No leave data');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee', 'used', 'ใช้ไป', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee' AND label_key='used');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee', 'remaining', 'เหลือ', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee' AND label_key='remaining');

-- Work Statistics
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee', 'Work Statistics', 'สถิติการทำงาน', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee' AND label_key='Work Statistics');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee', 'This Week', 'สัปดาห์นี้', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee' AND label_key='This Week');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee', 'This Month', 'เดือนนี้', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee' AND label_key='This Month');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee', 'Remaining', 'เวลาคงเหลือ', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee' AND label_key='Remaining');

-- Quick Actions
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee', 'Quick Actions', 'เมนูลัด', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee' AND label_key='Quick Actions');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee', 'My Attendance', 'การเข้างานของฉัน', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee' AND label_key='My Attendance');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee', 'My Leaves', 'การลาของฉัน', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee' AND label_key='My Leaves');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee', 'My Salary', 'เงินเดือนของฉัน', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee' AND label_key='My Salary');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee', 'My Profile', 'โปรไฟล์ของฉัน', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee' AND label_key='My Profile');

-- My Info
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee', 'My Info', 'ข้อมูลของฉัน', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee' AND label_key='My Info');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee', 'Employee ID', 'รหัสพนักงาน', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee' AND label_key='Employee ID');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee', 'Email', 'อีเมล', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee' AND label_key='Email');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee', 'Department', 'แผนก', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee' AND label_key='Department');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee', 'Designation', 'ตำแหน่ง', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee' AND label_key='Designation');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee', 'Join Date', 'วันที่เริ่มงาน', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee' AND label_key='Join Date');

-- Leave Requests
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee', 'Leave Requests', 'คำขอลา', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee' AND label_key='Leave Requests');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee', 'Total Requests', 'คำขอทั้งหมด', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee' AND label_key='Total Requests');

-- ═══════════════════════════════════════════════════════════════════
-- English (en) translations
-- ═══════════════════════════════════════════════════════════════════

INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'employee', 'Loading dashboard...', 'Loading dashboard...', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='en' AND page_key='employee' AND label_key='Loading dashboard...');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'employee', 'Welcome Back', 'Welcome Back', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='en' AND page_key='employee' AND label_key='Welcome Back');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'employee', 'View Profile', 'View Profile', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='en' AND page_key='employee' AND label_key='View Profile');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'employee', 'Timesheet', 'Timesheet', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='en' AND page_key='employee' AND label_key='Timesheet');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'employee', 'Today', 'Today', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='en' AND page_key='employee' AND label_key='Today');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'employee', 'Check In', 'Check In', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='en' AND page_key='employee' AND label_key='Check In');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'employee', 'Check Out', 'Check Out', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='en' AND page_key='employee' AND label_key='Check Out');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'employee', 'Punch In', 'Punch In', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='en' AND page_key='employee' AND label_key='Punch In');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'employee', 'Punch Out', 'Punch Out', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='en' AND page_key='employee' AND label_key='Punch Out');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'employee', 'Punch Completed', 'Punch Completed', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='en' AND page_key='employee' AND label_key='Punch Completed');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'employee', 'Production', 'Production', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='en' AND page_key='employee' AND label_key='Production');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'employee', 'Overtime', 'Overtime', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='en' AND page_key='employee' AND label_key='Overtime');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'employee', 'Break', 'Break', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='en' AND page_key='employee' AND label_key='Break');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'employee', 'Hrs', 'Hrs', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='en' AND page_key='employee' AND label_key='Hrs');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'employee', 'Min', 'Min', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='en' AND page_key='employee' AND label_key='Min');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'employee', 'View Attendance', 'View Attendance', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='en' AND page_key='employee' AND label_key='View Attendance');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'employee', 'Upcoming Holidays', 'Upcoming Holidays', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='en' AND page_key='employee' AND label_key='Upcoming Holidays');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'employee', 'View All', 'View All', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='en' AND page_key='employee' AND label_key='View All');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'employee', 'No upcoming holidays', 'No upcoming holidays', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='en' AND page_key='employee' AND label_key='No upcoming holidays');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'employee', 'Holidays', 'Holidays', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='en' AND page_key='employee' AND label_key='Holidays');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'employee', 'Attendance & Leaves', 'Attendance & Leaves', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='en' AND page_key='employee' AND label_key='Attendance & Leaves');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'employee', 'Total Leaves', 'Total Leaves', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='en' AND page_key='employee' AND label_key='Total Leaves');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'employee', 'Leaves Taken', 'Leaves Taken', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='en' AND page_key='employee' AND label_key='Leaves Taken');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'employee', 'Available', 'Available', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='en' AND page_key='employee' AND label_key='Available');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'employee', 'Pending', 'Pending', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='en' AND page_key='employee' AND label_key='Pending');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'employee', 'Approved', 'Approved', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='en' AND page_key='employee' AND label_key='Approved');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'employee', 'Rejected', 'Rejected', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='en' AND page_key='employee' AND label_key='Rejected');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'employee', 'Apply Leave', 'Apply Leave', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='en' AND page_key='employee' AND label_key='Apply Leave');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'employee', 'Leave Balance', 'Leave Balance', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='en' AND page_key='employee' AND label_key='Leave Balance');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'employee', 'No leave data', 'No leave data', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='en' AND page_key='employee' AND label_key='No leave data');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'employee', 'used', 'used', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='en' AND page_key='employee' AND label_key='used');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'employee', 'remaining', 'remaining', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='en' AND page_key='employee' AND label_key='remaining');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'employee', 'Work Statistics', 'Work Statistics', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='en' AND page_key='employee' AND label_key='Work Statistics');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'employee', 'This Week', 'This Week', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='en' AND page_key='employee' AND label_key='This Week');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'employee', 'This Month', 'This Month', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='en' AND page_key='employee' AND label_key='This Month');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'employee', 'Remaining', 'Remaining', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='en' AND page_key='employee' AND label_key='Remaining');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'employee', 'Quick Actions', 'Quick Actions', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='en' AND page_key='employee' AND label_key='Quick Actions');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'employee', 'My Attendance', 'My Attendance', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='en' AND page_key='employee' AND label_key='My Attendance');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'employee', 'My Leaves', 'My Leaves', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='en' AND page_key='employee' AND label_key='My Leaves');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'employee', 'My Salary', 'My Salary', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='en' AND page_key='employee' AND label_key='My Salary');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'employee', 'My Profile', 'My Profile', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='en' AND page_key='employee' AND label_key='My Profile');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'employee', 'My Info', 'My Info', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='en' AND page_key='employee' AND label_key='My Info');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'employee', 'Employee ID', 'Employee ID', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='en' AND page_key='employee' AND label_key='Employee ID');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'employee', 'Email', 'Email', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='en' AND page_key='employee' AND label_key='Email');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'employee', 'Department', 'Department', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='en' AND page_key='employee' AND label_key='Department');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'employee', 'Designation', 'Designation', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='en' AND page_key='employee' AND label_key='Designation');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'employee', 'Join Date', 'Join Date', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='en' AND page_key='employee' AND label_key='Join Date');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'employee', 'Leave Requests', 'Leave Requests', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='en' AND page_key='employee' AND label_key='Leave Requests');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'employee', 'Total Requests', 'Total Requests', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='en' AND page_key='employee' AND label_key='Total Requests');

-- Leave Quota (new label)
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee', 'Leave Quota', 'โควต้าวันลา', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee' AND label_key='Leave Quota');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'employee', 'Leave Quota', 'Leave Quota', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='en' AND page_key='employee' AND label_key='Leave Quota');
