-- ═══════════════════════════════════════════════════════════════
-- Bilingual Header & Common Translations (EN + TH)
-- Generated: 2026-03-16
-- Table: "solution-one"."adm-tb-ms-language-translations"
-- ═══════════════════════════════════════════════════════════════
-- These translations cover header, sidebar, and common UI labels
-- that are shared across all pages.
-- ═══════════════════════════════════════════════════════════════

-- ── header (profile dropdown & layout) ──
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'header', 'My Profile', 'My Profile', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'en' AND page_key = 'header' AND label_key = 'My Profile');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'header', 'My Profile', 'โปรไฟล์ของฉัน', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'th' AND page_key = 'header' AND label_key = 'My Profile');

INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'header', 'Change Password', 'Change Password', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'en' AND page_key = 'header' AND label_key = 'Change Password');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'header', 'Change Password', 'เปลี่ยนรหัสผ่าน', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'th' AND page_key = 'header' AND label_key = 'Change Password');

INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'header', 'Settings', 'Settings', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'en' AND page_key = 'header' AND label_key = 'Settings');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'header', 'Settings', 'ตั้งค่า', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'th' AND page_key = 'header' AND label_key = 'Settings');

INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'header', 'Logout', 'Logout', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'en' AND page_key = 'header' AND label_key = 'Logout');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'header', 'Logout', 'ออกจากระบบ', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'th' AND page_key = 'header' AND label_key = 'Logout');

INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'header', 'Admin', 'Admin', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'en' AND page_key = 'header' AND label_key = 'Admin');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'header', 'Admin', 'ผู้ดูแลระบบ', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'th' AND page_key = 'header' AND label_key = 'Admin');

-- ── common (shared across all pages — sidebar messages, buttons, etc.) ──
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'common', 'Loading menus...', 'Loading menus...', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'en' AND page_key = 'common' AND label_key = 'Loading menus...');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'common', 'Loading menus...', 'กำลังโหลดเมนู...', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'th' AND page_key = 'common' AND label_key = 'Loading menus...');

INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'common', 'Failed to load menus', 'Failed to load menus', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'en' AND page_key = 'common' AND label_key = 'Failed to load menus');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'common', 'Failed to load menus', 'โหลดเมนูล้มเหลว', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'th' AND page_key = 'common' AND label_key = 'Failed to load menus');

INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'common', 'Retry', 'Retry', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'en' AND page_key = 'common' AND label_key = 'Retry');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'common', 'Retry', 'ลองอีกครั้ง', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'th' AND page_key = 'common' AND label_key = 'Retry');

INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'common', 'Dashboard', 'Dashboard', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'en' AND page_key = 'common' AND label_key = 'Dashboard');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'common', 'Dashboard', 'หน้าหลัก', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'th' AND page_key = 'common' AND label_key = 'Dashboard');

INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'common', 'Search', 'Search', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'en' AND page_key = 'common' AND label_key = 'Search');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'common', 'Search', 'ค้นหา', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'th' AND page_key = 'common' AND label_key = 'Search');

INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'common', 'Clear', 'Clear', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'en' AND page_key = 'common' AND label_key = 'Clear');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'common', 'Clear', 'ล้าง', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'th' AND page_key = 'common' AND label_key = 'Clear');

INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'common', 'Add', 'Add', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'en' AND page_key = 'common' AND label_key = 'Add');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'common', 'Add', 'เพิ่ม', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'th' AND page_key = 'common' AND label_key = 'Add');

INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'common', 'Edit', 'Edit', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'en' AND page_key = 'common' AND label_key = 'Edit');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'common', 'Edit', 'แก้ไข', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'th' AND page_key = 'common' AND label_key = 'Edit');

INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'common', 'Delete', 'Delete', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'en' AND page_key = 'common' AND label_key = 'Delete');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'common', 'Delete', 'ลบ', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'th' AND page_key = 'common' AND label_key = 'Delete');

INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'common', 'Save', 'Save', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'en' AND page_key = 'common' AND label_key = 'Save');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'common', 'Save', 'บันทึก', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'th' AND page_key = 'common' AND label_key = 'Save');

INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'common', 'Cancel', 'Cancel', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'en' AND page_key = 'common' AND label_key = 'Cancel');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'common', 'Cancel', 'ยกเลิก', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'th' AND page_key = 'common' AND label_key = 'Cancel');

INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'common', 'Submit', 'Submit', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'en' AND page_key = 'common' AND label_key = 'Submit');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'common', 'Submit', 'ส่ง', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'th' AND page_key = 'common' AND label_key = 'Submit');

INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'common', 'Close', 'Close', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'en' AND page_key = 'common' AND label_key = 'Close');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'common', 'Close', 'ปิด', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'th' AND page_key = 'common' AND label_key = 'Close');

INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'common', 'Confirm', 'Confirm', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'en' AND page_key = 'common' AND label_key = 'Confirm');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'common', 'Confirm', 'ยืนยัน', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'th' AND page_key = 'common' AND label_key = 'Confirm');

INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'common', 'Actions', 'Actions', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'en' AND page_key = 'common' AND label_key = 'Actions');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'common', 'Actions', 'จัดการ', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'th' AND page_key = 'common' AND label_key = 'Actions');

INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'common', 'Status', 'Status', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'en' AND page_key = 'common' AND label_key = 'Status');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'common', 'Status', 'สถานะ', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'th' AND page_key = 'common' AND label_key = 'Status');

INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'common', 'Name', 'Name', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'en' AND page_key = 'common' AND label_key = 'Name');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'common', 'Name', 'ชื่อ', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'th' AND page_key = 'common' AND label_key = 'Name');

INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'common', 'Email', 'Email', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'en' AND page_key = 'common' AND label_key = 'Email');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'common', 'Email', 'อีเมล', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'th' AND page_key = 'common' AND label_key = 'Email');

INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'common', 'Department', 'Department', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'en' AND page_key = 'common' AND label_key = 'Department');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'common', 'Department', 'แผนก', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'th' AND page_key = 'common' AND label_key = 'Department');

INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'common', 'Employee', 'Employee', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'en' AND page_key = 'common' AND label_key = 'Employee');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'common', 'Employee', 'พนักงาน', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'th' AND page_key = 'common' AND label_key = 'Employee');

INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'common', 'Date', 'Date', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'en' AND page_key = 'common' AND label_key = 'Date');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'common', 'Date', 'วันที่', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'th' AND page_key = 'common' AND label_key = 'Date');

INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'common', 'Type', 'Type', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'en' AND page_key = 'common' AND label_key = 'Type');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'common', 'Type', 'ประเภท', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'th' AND page_key = 'common' AND label_key = 'Type');

INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'common', 'Description', 'Description', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'en' AND page_key = 'common' AND label_key = 'Description');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'common', 'Description', 'รายละเอียด', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'th' AND page_key = 'common' AND label_key = 'Description');

INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'common', 'No Data Found', 'No Data Found', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'en' AND page_key = 'common' AND label_key = 'No Data Found');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'common', 'No Data Found', 'ไม่พบข้อมูล', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'th' AND page_key = 'common' AND label_key = 'No Data Found');

INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'common', 'Save Changes', 'Save Changes', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'en' AND page_key = 'common' AND label_key = 'Save Changes');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'common', 'Save Changes', 'บันทึกการเปลี่ยนแปลง', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'th' AND page_key = 'common' AND label_key = 'Save Changes');

INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'common', 'Are you sure?', 'Are you sure?', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'en' AND page_key = 'common' AND label_key = 'Are you sure?');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'common', 'Are you sure?', 'คุณแน่ใจหรือไม่?', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'th' AND page_key = 'common' AND label_key = 'Are you sure?');

INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'common', 'Success!', 'Success!', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'en' AND page_key = 'common' AND label_key = 'Success!');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'common', 'Success!', 'สำเร็จ!', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'th' AND page_key = 'common' AND label_key = 'Success!');

INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'common', 'Error!', 'Error!', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'en' AND page_key = 'common' AND label_key = 'Error!');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'common', 'Error!', 'เกิดข้อผิดพลาด!', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'th' AND page_key = 'common' AND label_key = 'Error!');

INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'common', 'OK', 'OK', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'en' AND page_key = 'common' AND label_key = 'OK');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'common', 'OK', 'ตกลง', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'th' AND page_key = 'common' AND label_key = 'OK');

INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'common', 'Approve', 'Approve', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'en' AND page_key = 'common' AND label_key = 'Approve');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'common', 'Approve', 'อนุมัติ', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'th' AND page_key = 'common' AND label_key = 'Approve');

INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'common', 'Reject', 'Reject', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'en' AND page_key = 'common' AND label_key = 'Reject');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'common', 'Reject', 'ปฏิเสธ', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'th' AND page_key = 'common' AND label_key = 'Reject');

INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'common', 'View', 'View', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'en' AND page_key = 'common' AND label_key = 'View');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'common', 'View', 'ดู', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'th' AND page_key = 'common' AND label_key = 'View');

INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'common', 'Export', 'Export', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'en' AND page_key = 'common' AND label_key = 'Export');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'common', 'Export', 'ส่งออก', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'th' AND page_key = 'common' AND label_key = 'Export');

INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'common', 'Import', 'Import', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'en' AND page_key = 'common' AND label_key = 'Import');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'common', 'Import', 'นำเข้า', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'th' AND page_key = 'common' AND label_key = 'Import');

INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'common', 'Total', 'Total', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'en' AND page_key = 'common' AND label_key = 'Total');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'common', 'Total', 'ทั้งหมด', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'th' AND page_key = 'common' AND label_key = 'Total');

INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'common', 'From', 'From', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'en' AND page_key = 'common' AND label_key = 'From');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'common', 'From', 'จาก', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'th' AND page_key = 'common' AND label_key = 'From');

INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'common', 'To', 'To', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'en' AND page_key = 'common' AND label_key = 'To');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'common', 'To', 'ถึง', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'th' AND page_key = 'common' AND label_key = 'To');

INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'common', 'Designation', 'Designation', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'en' AND page_key = 'common' AND label_key = 'Designation');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'common', 'Designation', 'ตำแหน่ง', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'th' AND page_key = 'common' AND label_key = 'Designation');

INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'common', 'Phone', 'Phone', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'en' AND page_key = 'common' AND label_key = 'Phone');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'common', 'Phone', 'โทรศัพท์', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'th' AND page_key = 'common' AND label_key = 'Phone');

INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'common', 'Address', 'Address', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'en' AND page_key = 'common' AND label_key = 'Address');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'common', 'Address', 'ที่อยู่', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'th' AND page_key = 'common' AND label_key = 'Address');

INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'common', 'First Name', 'First Name', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'en' AND page_key = 'common' AND label_key = 'First Name');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'common', 'First Name', 'ชื่อ', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'th' AND page_key = 'common' AND label_key = 'First Name');

INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'common', 'Last Name', 'Last Name', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'en' AND page_key = 'common' AND label_key = 'Last Name');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'common', 'Last Name', 'นามสกุล', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code = 'th' AND page_key = 'common' AND label_key = 'Last Name');

-- ═══════════════════════════════════════════════════════════════
-- END OF BILINGUAL SEED DATA
-- Total: 74 INSERT statements (37 EN + 37 TH)
-- ═══════════════════════════════════════════════════════════════
