-- Employee Profile Page Translations (page_key = 'employee-profile')
-- NOTE: derivePageKey('/employees/employee-profile/0') => 'employee-profile'

-- Tabs
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee-profile', 'Profile', 'โปรไฟล์', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee-profile' AND label_key='Profile');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee-profile', 'Personal Info', 'ข้อมูลส่วนตัว', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee-profile' AND label_key='Personal Info');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee-profile', 'Emergency', 'ฉุกเฉิน', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee-profile' AND label_key='Emergency');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee-profile', 'Bank', 'ธนาคาร', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee-profile' AND label_key='Bank');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee-profile', 'Education', 'การศึกษา', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee-profile' AND label_key='Education');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee-profile', 'Experience', 'ประสบการณ์', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee-profile' AND label_key='Experience');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee-profile', 'Family', 'ครอบครัว', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee-profile' AND label_key='Family');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee-profile', 'Employment', 'การจ้างงาน', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee-profile' AND label_key='Employment');

-- Section headers
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee-profile', 'Profile Information', 'ข้อมูลโปรไฟล์', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee-profile' AND label_key='Profile Information');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee-profile', 'Personal Information', 'ข้อมูลส่วนบุคคล', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee-profile' AND label_key='Personal Information');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee-profile', 'Emergency Contacts', 'ผู้ติดต่อฉุกเฉิน', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee-profile' AND label_key='Emergency Contacts');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee-profile', 'Bank Information', 'ข้อมูลธนาคาร', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee-profile' AND label_key='Bank Information');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee-profile', 'Family Information', 'ข้อมูลครอบครัว', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee-profile' AND label_key='Family Information');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee-profile', 'Employment History', 'ประวัติการจ้างงาน', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee-profile' AND label_key='Employment History');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee-profile', 'Primary Contact', 'ผู้ติดต่อหลัก', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee-profile' AND label_key='Primary Contact');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee-profile', 'Secondary Contact', 'ผู้ติดต่อรอง', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee-profile' AND label_key='Secondary Contact');

-- Profile fields
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee-profile', 'First Name', 'ชื่อ', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee-profile' AND label_key='First Name');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee-profile', 'Last Name', 'นามสกุล', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee-profile' AND label_key='Last Name');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee-profile', 'Email', 'อีเมล', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee-profile' AND label_key='Email');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee-profile', 'Phone', 'โทรศัพท์', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee-profile' AND label_key='Phone');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee-profile', 'Birth Date', 'วันเกิด', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee-profile' AND label_key='Birth Date');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee-profile', 'Address', 'ที่อยู่', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee-profile' AND label_key='Address');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee-profile', 'Department', 'แผนก', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee-profile' AND label_key='Department');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee-profile', 'Designation', 'ตำแหน่ง', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee-profile' AND label_key='Designation');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee-profile', 'Role', 'บทบาท', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee-profile' AND label_key='Role');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee-profile', 'Gender', 'เพศ', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee-profile' AND label_key='Gender');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee-profile', 'State', 'จังหวัด', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee-profile' AND label_key='State');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee-profile', 'Country', 'ประเทศ', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee-profile' AND label_key='Country');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee-profile', 'Pin Code', 'รหัสไปรษณีย์', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee-profile' AND label_key='Pin Code');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee-profile', 'Employee ID', 'รหัสพนักงาน', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee-profile' AND label_key='Employee ID');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee-profile', 'Reports To', 'รายงานต่อ', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee-profile' AND label_key='Reports To');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee-profile', 'Organization', 'องค์กร', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee-profile' AND label_key='Organization');

-- Personal Info fields
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee-profile', 'Passport No', 'เลขที่หนังสือเดินทาง', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee-profile' AND label_key='Passport No');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee-profile', 'Passport Expiry', 'วันหมดอายุหนังสือเดินทาง', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee-profile' AND label_key='Passport Expiry');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee-profile', 'Tel', 'โทรศัพท์', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee-profile' AND label_key='Tel');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee-profile', 'Nationality', 'สัญชาติ', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee-profile' AND label_key='Nationality');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee-profile', 'Religion', 'ศาสนา', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee-profile' AND label_key='Religion');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee-profile', 'Marital Status', 'สถานภาพสมรส', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee-profile' AND label_key='Marital Status');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee-profile', 'Employment of Spouse', 'อาชีพคู่สมรส', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee-profile' AND label_key='Employment of Spouse');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee-profile', 'No. of Children', 'จำนวนบุตร', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee-profile' AND label_key='No. of Children');

-- Emergency fields
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee-profile', 'Name', 'ชื่อ', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee-profile' AND label_key='Name');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee-profile', 'Relationship', 'ความสัมพันธ์', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee-profile' AND label_key='Relationship');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee-profile', 'Phone 1', 'โทรศัพท์ 1', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee-profile' AND label_key='Phone 1');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee-profile', 'Phone 2', 'โทรศัพท์ 2', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee-profile' AND label_key='Phone 2');

-- Bank fields
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee-profile', 'Account No', 'เลขที่บัญชี', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee-profile' AND label_key='Account No');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee-profile', 'Bank Code', 'รหัสธนาคาร', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee-profile' AND label_key='Bank Code');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee-profile', 'Branch', 'สาขา', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee-profile' AND label_key='Branch');

-- Education fields
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee-profile', 'Institution', 'สถาบัน', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee-profile' AND label_key='Institution');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee-profile', 'Subject', 'วิชา', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee-profile' AND label_key='Subject');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee-profile', 'Start', 'เริ่ม', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee-profile' AND label_key='Start');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee-profile', 'Complete', 'สำเร็จ', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee-profile' AND label_key='Complete');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee-profile', 'Degree', 'ปริญญา', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee-profile' AND label_key='Degree');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee-profile', 'Grade', 'เกรด', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee-profile' AND label_key='Grade');

-- Experience fields
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee-profile', 'Company', 'บริษัท', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee-profile' AND label_key='Company');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee-profile', 'Location', 'สถานที่', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee-profile' AND label_key='Location');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee-profile', 'Position', 'ตำแหน่ง', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee-profile' AND label_key='Position');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee-profile', 'From', 'จาก', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee-profile' AND label_key='From');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee-profile', 'To', 'ถึง', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee-profile' AND label_key='To');

-- Family fields
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee-profile', 'Date of Birth', 'วันเกิด', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee-profile' AND label_key='Date of Birth');

-- Employment fields
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee-profile', 'Salary', 'เงินเดือน', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee-profile' AND label_key='Salary');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee-profile', 'Effective Date', 'วันที่มีผล', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee-profile' AND label_key='Effective Date');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee-profile', 'Payment Type', 'ประเภทการจ่าย', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee-profile' AND label_key='Payment Type');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee-profile', 'Employee Type', 'ประเภทพนักงาน', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee-profile' AND label_key='Employee Type');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee-profile', 'End', 'สิ้นสุด', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee-profile' AND label_key='End');

-- Buttons & actions
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee-profile', 'Edit', 'แก้ไข', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee-profile' AND label_key='Edit');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee-profile', 'Save', 'บันทึก', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee-profile' AND label_key='Save');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee-profile', 'Saving...', 'กำลังบันทึก...', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee-profile' AND label_key='Saving...');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee-profile', 'Back to Employees', 'กลับไปรายชื่อพนักงาน', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee-profile' AND label_key='Back to Employees');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee-profile', 'Select', 'เลือก', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee-profile' AND label_key='Select');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee-profile', 'Add', 'เพิ่ม', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee-profile' AND label_key='Add');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee-profile', 'Close', 'ปิด', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee-profile' AND label_key='Close');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee-profile', 'Apply', 'นำไปใช้', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee-profile' AND label_key='Apply');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee-profile', 'New Employee', 'พนักงานใหม่', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee-profile' AND label_key='New Employee');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee-profile', 'Active', 'ใช้งาน', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee-profile' AND label_key='Active');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee-profile', 'Inactive', 'ไม่ใช้งาน', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee-profile' AND label_key='Inactive');

-- Empty states
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee-profile', 'No education records', 'ไม่มีข้อมูลการศึกษา', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee-profile' AND label_key='No education records');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee-profile', 'No experience records', 'ไม่มีข้อมูลประสบการณ์', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee-profile' AND label_key='No experience records');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee-profile', 'No family members', 'ไม่มีข้อมูลครอบครัว', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee-profile' AND label_key='No family members');
