-- Management Pages Bilingual Translations (EN + TH)
-- Covers: menu sidebar label, admin dashboard, employee dashboard

-- ═══ MENU SIDEBAR (page_key='menu') ═══
-- "Management Dashboard" menu item — label_key should match the MenuCode or Base of menusId=90
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'menu', 'admin', 'แดชบอร์ดผู้บริหาร', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='menu' AND label_key='admin');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'en', 'menu', 'admin', 'Management Dashboard', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='en' AND page_key='menu' AND label_key='admin');

-- Also update TitleTh on the menu table directly (menusId=90)
UPDATE "solution-one"."auth-tb-ms-menus" SET title_th = 'แดชบอร์ดผู้บริหาร' WHERE menus_id = 90 AND (title_th IS NULL OR title_th = '');

-- ═══ ADMIN DASHBOARD (page_key='admin') ═══
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'admin', 'Welcome Admin!', 'ยินดีต้อนรับ ผู้ดูแลระบบ!', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='admin' AND label_key='Welcome Admin!');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'admin', 'Projects', 'โครงการ', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='admin' AND label_key='Projects');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'admin', 'Clients', 'ลูกค้า', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='admin' AND label_key='Clients');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'admin', 'Tasks', 'งาน', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='admin' AND label_key='Tasks');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'admin', 'Employees', 'พนักงาน', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='admin' AND label_key='Employees');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'admin', 'Total Revenue', 'รายได้ทั้งหมด', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='admin' AND label_key='Total Revenue');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'admin', 'Total Income', 'รายรับทั้งหมด', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='admin' AND label_key='Total Income');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'admin', 'Total Outcome', 'รายจ่ายทั้งหมด', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='admin' AND label_key='Total Outcome');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'admin', 'Sales Overview', 'ภาพรวมยอดขาย', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='admin' AND label_key='Sales Overview');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'admin', 'New Employees', 'พนักงานใหม่', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='admin' AND label_key='New Employees');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'admin', 'Earnings', 'รายได้', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='admin' AND label_key='Earnings');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'admin', 'Expenses', 'ค่าใช้จ่าย', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='admin' AND label_key='Expenses');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'admin', 'Profit', 'กำไร', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='admin' AND label_key='Profit');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'admin', 'Statistics', 'สถิติ', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='admin' AND label_key='Statistics');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'admin', 'Today Leave', 'ลาวันนี้', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='admin' AND label_key='Today Leave');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'admin', 'Pending Invoice', 'ใบแจ้งหนี้ค้าง', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='admin' AND label_key='Pending Invoice');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'admin', 'Completed Projects', 'โครงการเสร็จสิ้น', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='admin' AND label_key='Completed Projects');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'admin', 'Open Tickets', 'ตั๋วเปิด', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='admin' AND label_key='Open Tickets');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'admin', 'Closed Tickets', 'ตั๋วปิด', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='admin' AND label_key='Closed Tickets');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'admin', 'Task Statistics', 'สถิติงาน', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='admin' AND label_key='Task Statistics');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'admin', 'Total Tasks', 'งานทั้งหมด', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='admin' AND label_key='Total Tasks');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'admin', 'Overdue Tasks', 'งานเลยกำหนด', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='admin' AND label_key='Overdue Tasks');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'admin', 'Completed Tasks', 'งานเสร็จสิ้น', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='admin' AND label_key='Completed Tasks');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'admin', 'Inprogress Tasks', 'งานกำลังดำเนินการ', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='admin' AND label_key='Inprogress Tasks');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'admin', 'On Hold Tasks', 'งานพักไว้', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='admin' AND label_key='On Hold Tasks');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'admin', 'Pending Tasks', 'งานรอดำเนินการ', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='admin' AND label_key='Pending Tasks');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'admin', 'Review Tasks', 'งานรอตรวจสอบ', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='admin' AND label_key='Review Tasks');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'admin', 'Today Absent', 'ขาดงานวันนี้', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='admin' AND label_key='Today Absent');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'admin', 'Load More', 'โหลดเพิ่มเติม', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='admin' AND label_key='Load More');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'admin', 'Invoices', 'ใบแจ้งหนี้', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='admin' AND label_key='Invoices');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'admin', 'Invoice ID', 'เลขที่ใบแจ้งหนี้', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='admin' AND label_key='Invoice ID');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'admin', 'Client', 'ลูกค้า', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='admin' AND label_key='Client');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'admin', 'Due Date', 'วันครบกำหนด', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='admin' AND label_key='Due Date');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'admin', 'Payments', 'การชำระเงิน', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='admin' AND label_key='Payments');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'admin', 'Payment Type', 'ประเภทการชำระ', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='admin' AND label_key='Payment Type');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'admin', 'Paid Date', 'วันที่ชำระ', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='admin' AND label_key='Paid Date');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'admin', 'Paid Amount', 'จำนวนที่ชำระ', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='admin' AND label_key='Paid Amount');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'admin', 'View all invoices', 'ดูใบแจ้งหนี้ทั้งหมด', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='admin' AND label_key='View all invoices');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'admin', 'View all payments', 'ดูการชำระเงินทั้งหมด', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='admin' AND label_key='View all payments');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'admin', 'View all clients', 'ดูลูกค้าทั้งหมด', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='admin' AND label_key='View all clients');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'admin', 'Recent Projects', 'โครงการล่าสุด', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='admin' AND label_key='Recent Projects');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'admin', 'Project Name', 'ชื่อโครงการ', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='admin' AND label_key='Project Name');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'admin', 'Progress', 'ความคืบหน้า', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='admin' AND label_key='Progress');

-- ═══ EMPLOYEE DASHBOARD (page_key='employee') ═══
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee', 'View Profile', 'ดูโปรไฟล์', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee' AND label_key='View Profile');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee', 'Statistics', 'สถิติ', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee' AND label_key='Statistics');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee', 'Work In at', 'เข้างานเวลา', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee' AND label_key='Work In at');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee', 'Punch In', 'ลงเวลาเข้า', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee' AND label_key='Punch In');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee', 'Punch Out', 'ลงเวลาออก', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee' AND label_key='Punch Out');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee', 'Punch Completed', 'ลงเวลาครบแล้ว', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee' AND label_key='Punch Completed');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee', 'Remaining', 'เหลือ', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee' AND label_key='Remaining');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee', 'Overtime', 'ล่วงเวลา', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee' AND label_key='Overtime');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee', 'Break', 'พัก', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee' AND label_key='Break');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee', 'View Attendance', 'ดูการเข้างาน', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee' AND label_key='View Attendance');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee', 'Upcoming Holidays', 'วันหยุดที่จะถึง', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee' AND label_key='Upcoming Holidays');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee', 'View All', 'ดูทั้งหมด', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee' AND label_key='View All');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee', 'Attendance & Leaves', 'การเข้างานและการลา', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee' AND label_key='Attendance & Leaves');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee', 'Total Leaves', 'วันลาทั้งหมด', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee' AND label_key='Total Leaves');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee', 'Leaves Taken', 'วันลาที่ใช้', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee' AND label_key='Leaves Taken');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee', 'Leaves Absent', 'วันลาขาด', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee' AND label_key='Leaves Absent');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee', 'Pending Approval', 'รอการอนุมัติ', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee' AND label_key='Pending Approval');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee', 'Working Days', 'วันทำงาน', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee' AND label_key='Working Days');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee', 'Loss of Pay', 'หักเงินเดือน', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee' AND label_key='Loss of Pay');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee', 'Apply Leave', 'ยื่นใบลา', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee' AND label_key='Apply Leave');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee', 'Working Hours', 'ชั่วโมงทำงาน', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee' AND label_key='Working Hours');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee', 'This Week', 'สัปดาห์นี้', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee' AND label_key='This Week');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee', 'Hours', 'ชั่วโมง', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee' AND label_key='Hours');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee', 'Important', 'สำคัญ', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee' AND label_key='Important');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee', 'Notifications', 'การแจ้งเตือน', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee' AND label_key='Notifications');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee', 'Schedules', 'ตารางเวลา', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee' AND label_key='Schedules');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee', 'On Going Projects', 'โครงการที่ดำเนินอยู่', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee' AND label_key='On Going Projects');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee', 'Total Tasks', 'งานทั้งหมด', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee' AND label_key='Total Tasks');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee', 'Completed', 'เสร็จสิ้น', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee' AND label_key='Completed');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee', 'Deadline', 'กำหนดส่ง', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee' AND label_key='Deadline');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee', 'Today', 'วันนี้', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee' AND label_key='Today');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee', 'Welcome Back,', 'ยินดีต้อนรับกลับ,', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee' AND label_key='Welcome Back,');
INSERT INTO "solution-one"."adm-tb-ms-language-translations" (language_code, page_key, label_key, label_value, create_date, create_by) SELECT 'th', 'employee', 'Leave Date', 'วันที่ลา', NOW(), 'system' WHERE NOT EXISTS (SELECT 1 FROM "solution-one"."adm-tb-ms-language-translations" WHERE language_code='th' AND page_key='employee' AND label_key='Leave Date');

-- ═══ END ═══
-- Total: ~75 INSERT statements for management pages
