/**
 * Scan all backoffice TSX/TS files for t('bo.*', 'fallback') calls
 * and generate a manifest file with all discovered keys.
 * 
 * Usage: node scripts/scan-bo-keys.js
 * Output: src/generated/bo-keys-manifest.ts
 */

const fs = require('fs');
const path = require('path');

const SRC_DIR = path.join(__dirname, '..', 'src');
const OUTPUT_FILE = path.join(SRC_DIR, 'generated', 'bo-keys-manifest.ts');

// Recursively find all .tsx and .ts files
function findFiles(dir, ext = ['.tsx', '.ts']) {
    const results = [];
    const entries = fs.readdirSync(dir, { withFileTypes: true });
    for (const entry of entries) {
        const fullPath = path.join(dir, entry.name);
        if (entry.isDirectory() && !entry.name.startsWith('.') && entry.name !== 'node_modules' && entry.name !== 'generated') {
            results.push(...findFiles(fullPath, ext));
        } else if (entry.isFile() && ext.some(e => entry.name.endsWith(e))) {
            results.push(fullPath);
        }
    }
    return results;
}

// Extract t('bo.xxx', 'fallback') patterns from source
function extractKeys(content) {
    const keys = {};
    // Pattern 1: t('bo.xxx.yyy', 'fallback text')
    const regex1 = /t\(\s*'(bo\.[^']+)'\s*,\s*'([^']*)'\s*\)/g;
    let match;
    while ((match = regex1.exec(content)) !== null) {
        if (!keys[match[1]]) keys[match[1]] = match[2];
    }
    // Pattern 2: labelKey: 'bo.xxx', labelDefault: 'fallback'
    const regex2 = /labelKey:\s*'(bo\.[^']+)'\s*,\s*labelDefault:\s*'([^']*)'/g;
    while ((match = regex2.exec(content)) !== null) {
        if (!keys[match[1]]) keys[match[1]] = match[2];
    }
    // Pattern 3: descKey: 'bo.xxx', descDefault: 'fallback'
    const regex3 = /descKey:\s*'(bo\.[^']+)'\s*,\s*descDefault:\s*'([^']*)'/g;
    while ((match = regex3.exec(content)) !== null) {
        if (!keys[match[1]]) keys[match[1]] = match[2];
    }
    return keys;
}

function main() {
    console.log('🔍 Scanning backoffice source files for bo.* keys...\n');

    const files = findFiles(SRC_DIR);
    const allKeys = {};
    let fileCount = 0;

    for (const file of files) {
        const content = fs.readFileSync(file, 'utf-8');
        const keys = extractKeys(content);
        const keyCount = Object.keys(keys).length;
        if (keyCount > 0) {
            Object.assign(allKeys, keys);
            const rel = path.relative(path.join(__dirname, '..'), file);
            console.log(`  📄 ${rel} → ${keyCount} keys`);
            fileCount++;
        }
    }

    // Sort keys
    const sortedKeys = Object.keys(allKeys).sort();
    console.log(`\n✅ Found ${sortedKeys.length} unique bo.* keys across ${fileCount} files.\n`);

    // Generate output
    const outputDir = path.dirname(OUTPUT_FILE);
    if (!fs.existsSync(outputDir)) {
        fs.mkdirSync(outputDir, { recursive: true });
    }

    const lines = sortedKeys.map(key => {
        const fallback = allKeys[key].replace(/'/g, "\\'");
        return `    '${key}': '${fallback}',`;
    });

    const output = `/**
 * Auto-generated manifest of all backoffice translation keys.
 * Generated by: node scripts/scan-bo-keys.js
 * Generated at: ${new Date().toISOString()}
 * 
 * DO NOT EDIT MANUALLY — run the scan script to regenerate.
 */

export const BO_KEYS_MANIFEST: Record<string, string> = {
${lines.join('\n')}
};
`;

    fs.writeFileSync(OUTPUT_FILE, output, 'utf-8');
    console.log(`📦 Written to: ${path.relative(path.join(__dirname, '..'), OUTPUT_FILE)}`);
    console.log(`   ${sortedKeys.length} keys total\n`);
}

main();
