name: Deploy to Production (nexusfx.biz)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
      - name: Execute Deployment Commands
        run: |
          cd /opt/nexsite/nex-site
          git pull origin main
          docker compose -p nexsite -f docker-compose.prod.yml down
          docker compose -p nexsite -f docker-compose.prod.yml up -d --build
